<ips:template parameters="$anim" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>   

  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj animacje po CMD">
  </div>  

<div class='ipsType_center ipsPad'>
<a href="index.php?/admincp/&action2=animsAddNew" data-ipsdialog data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Dodawanie nowej animacji">
    <span class="ipsButton ipsButton_medium ipsButton_positive">
      Dodaj nową animacje
    </span>
  </a> 
</div>  
<table id="sarpTable" class='ipsPad'>
      <tr class="header">
        <th>
        </th>
          <th  data-key="UID">					
            UID
          </th>	

          <th  data-key="CMDo">					
            CMD
          </th>	

          <th data-key="lib">	
            lib
          </th>   

          <th data-key="name">	
            name
          </th>

          <th data-key="speed">	
            speed
          </th>

          <th data-key="loop">	
            loop
          </th>

          <th data-key="lockx">	
            lockx
          </th>

          <th data-key="locky">	
            locky
          </th>

          <th data-key="freeze">	
            freeze
          </th>

          <th data-key="time">	
            time
          </th>

     
        </tr>
      {{foreach $anims as $row}}
   
        <tr>	
		<td>
             <a href="index.php?/admincp/&animsEdit={$row['uid']}" class="ipsType_positive ipsType_normal ipsPos_right ipsFaded ipsFaded_more ipsFaded_withHover" data-ipsdialog data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Edytowanie animacji"><i class="fa fa-pencil"></i></a>
          </td>
          <td data-title="UID">	
            <div>{$row['uid']}</div>
          </td> 

          <td data-title="CMDo">
            <div>{$row['command']}</div>
          </td>

          <td data-title="lib">	
            <div>{$row['animlib']}</div>
          </td> 

          <td data-title="name">	
            <div>{$row['animname']}</div>
          </td> 

          <td data-title="speed">	
            <div>{$row['speed']}</div>
          </td> 

          <td data-title="loop">	
            <div>{$row['loop']}</div>
          </td> 

          <td data-title="lockx">	
            <div>{$row['lockx']}</div>
          </td> 

          <td data-title="locky">	
            <div>{$row['locky']}</div>
          </td> 

          <td data-title="freeze">	
            <div >{$row['freeze']}</div>
          </td> 

          <td data-title="time">	
            <div >{$row['time']}</div>
          </td> 

   
		{{endforeach}}
      
    </table>
