<ips:template parameters="$cars_ownertype_player, $cars_ownertype_group" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[3];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script> 
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Pojazdy</h2>
<hr class="ipsHr">
<div class="ipsColumns">
  <div class="ipsColumn_fluid ipsType_center ipsAreaBackground ipsPad">
    <ul class='ipsButton_split'>
	<li><a href='index.php?app=game&module=admincp&tab=cars&owner=Players' class='ipsButton ipsButton_small {{if \IPS\Request::i()->owner == 'Players' }} ipsButton_primary {{else}} ipsButton_veryLight {{endelse}} {{endif}}'>Pojazdy należace do graczy</a></li>
	<li><a href='index.php?app=game&module=admincp&tab=cars&owner=Groups' class='ipsButton ipsButton_small  {{if \IPS\Request::i()->owner == 'Groups' }} ipsButton_primary {{else}} ipsButton_veryLight {{endelse}} {{endif}}'>Pojazdy należace do grup</a></li>
</ul>
  </div>
<hr class="ipsHr">
{{if \IPS\Request::i()->owner == 'Players' }}
<div class="ipsBox ipsPad">
  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj pojazd po uid właściciela">
  </div>

 <table id="sarpTable" class='ipsPad'>
  <tr class="header">
    <th  data-key="UID">					
              ID
            </th>	
            <th  data-key="Nazwa">					
              Model
            </th>	
            <th data-key="Typ właściciela">	
              Typ właściciela
            </th>           
            <th data-key="Właściciel">	
              Właściciel
            </th>                
            <th data-key="Właściciel">	
              Szczegóły
            </th>
  </tr>
 {{foreach $cars_ownertype_player as $player}}
        <tbody data-role="tableRows">
          <tr class="ipsClearfix" data-keynavblock="">	
            <td data-title="ID">	
              <div class="ipsDataItem_title ipsType_light">{$player['idpojazdu']}</div>
            </td>
            <td data-title="Nazwa">
              <div class="ipsDataItem_title">{$player['name']}</div>
            </td>
            <td data-title="Status">
              <div class="ipsDataItem_title">{$player['ownertype']}</div>
            </td>           
            <td data-title="Status">
              <div class="ipsDataItem_title">{$player['imie_nazwisko']} (ID: {$player['char_uid']})</div>
            </td>                  
            <td data-title="Status">
               <a class="ipsButton ipsButton_verySmall ipsButton_veryLight" 
               href="index.php?app=game&module=ajax&controller=manageCar&uid={$player['idpojazdu']}">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">Zarządzaj</h5></div>
              </a>
            </td>
          </tr>
        </tbody>
        {{endforeach}}
</table>
  
      <div style="clear: both"></div>
</div>
{{elseif \IPS\Request::i()->owner == 'Groups' }}
<div class="ipsBox ipsPad">
    <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj pojazd po właścicielu">
  </div>
  <table id="sarpTable">
  <tr class="header">
    <th  data-key="UID">					
              ID
            </th>	
            <th  data-key="Nazwa">					
              Model
            </th>	
            <th data-key="Typ właściciela">	
              Typ właściciela
            </th>           
            <th data-key="Właściciel">	
              ID grupy do której należy
            </th>                
            <th data-key="Właściciel">	
              Szczegóły
            </th>
  </tr>
      {{foreach $cars_ownertype_group as $group}}
        <tbody data-role="tableRows">
          <tr class="ipsClearfix" data-keynavblock="">	
            <td data-title="ID">	
              <div class="ipsDataItem_title ipsType_light">{$group['idpojazdu']}</div>
            </td>
            <td data-title="Nazwa">
              <div class="ipsDataItem_title">{$group['name']}</div>
            </td>
            <td data-title="Status">
              <div class="ipsDataItem_title">{$group['ownertype']}</div>
            </td>           
            <td data-title="Status">
              <div class="ipsDataItem_title">{$group['group_uid']} </div>
            </td>                  
            <td data-title="Status">
               <a class="ipsButton ipsButton_verySmall ipsButton_veryLight" 
               href="index.php?app=game&module=ajax&controller=manageCar&uid={$group['uid']}">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">Zarządzaj</h5></div>
              </a>
            </td>
          </tr>
        </tbody>
        {{endforeach}}
</table>
  
	
      <div style="clear: both"></div>
</div>
{{endelse}}
{{endif}}
