<ips:template parameters="$drugs" />
<div class="ipsBox">
  <form action="" method="POST">
    <table class="ipsTable ipsTable_responsive">
      <tr class="ipsAreaBackground">
        <td>
          <h2 class="ipsType_sectionTitle ipsType_reset">      
            Nazwa
          </h2>
        </td>
        <td>
          <h2 class="ipsType_sectionTitle ipsType_reset">      
            Cena minimalna
          </h2>
        </td>
        <td>
          <h2 class="ipsType_sectionTitle ipsType_reset">      
            Cena maksymalna
          </h2>
        </td>
      </tr>
      {{foreach $drugs as $row}}
        <tr>
          <td>
            {$row['type']}
          </td>
          <td>
            <input name="price_min[{$row['drug_type']}]" type="number" value="{$row['drug_price']}">
          </td>
          <td>
            <input name="price_max[{$row['drug_type']}]" type="number" value="{$row['drug_price_max']}">
          </td>
        </tr>
      {{endforeach}}
    </table>
    <div style="padding: 10px; text-align: center">
      <input type="submit">
    </div>
  </form>
</div>