<ips:template parameters="$dziwka" />
<table class="ipsTable ipsTable_responsive" data-role="table">
  
      <thead>
        <tr class="ipsAreaBackground">		

          <th  data-key="UID">					
            ID
          </th>	

          <th  data-key="Model">					
            Model
          </th>	

          <th data-key="Typ właściciela">	
            Treść
          </th>   
           <th data-key="Kasa przy niej">	
            Kasa przy niej
          </th>   
           <th data-key="Kosz jej wykupienia">	
            Koszt jej wykupienia
          </th>   
           <th data-key="Właściciel dziwki UID POSTACI">	
            Owner dziwki (UID POSTACI)
          </th>   
        </tr>
      </thead>
      {{foreach $dziwka as $row}}
      <tbody data-role="tableRows">
        <tr class="ipsClearfix" data-keynavblock="">	

          <td data-title="ID">	
            <div class="ipsDataItem_title ipsType_light">{$row['prostitute_uid']}</div>
          </td> 

           <td data-title="Model">	
             <div class="  ipsType_center"> <img src="https://h-rp.eu/images/skins/{$row['prostitute_skin']}.png" height="100" width="55"> </div>
          </td> 

          <td data-title="Treść">	
            <div class="ipsDataItem_title">{$row['prostitute_name']}</div>
          </td> 
          <td data-title="Kasa">	
            <div class="ipsDataItem_title">${$row['prostitute_cash']}</div>
          </td> 
          <td data-title="Cena">	
            <div class="ipsDataItem_title">${$row['prostitute_price']}</div>
          </td> 
          <td data-title="Owner">	
            <div class="ipsDataItem_title">{$row['prostitute_owner']}</div>
          </td> 
		{{endforeach}}
        </tr>
      </tbody>
    </table>
