<ips:template parameters="$groups" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>   

  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj grupe po nazwie">
  </div>

 <table id="sarpTable" class='ipsPad'>
  <tr class="header">
    <th>ID</th>
    <th>Nazwa</th>
    <th>TAG</th>
    <th>Typ grupy</th>
    <th>Zarządaj</th>
  </tr>
  {{foreach $groups as $row}}
    	<tr>
          <td>
            {$row['group_uid']}
          </td>
          <td>
            {$row['group_name']}
          </td>
          <td>
            {$row['group_tag']}
          </td>
          <td>
            {$row['group_type']}
          </td>
          <td>
             <a class="ipsButton ipsButton_verySmall ipsButton_veryLight" 
               href="index.php?app=game&module=ajax&controller=manageGroup&id={$row['id']}">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">Zarządzaj</h5></div>
              </a>
          </td>
      </tr>
  {{endforeach}}
</table>

