<ips:template parameters="$item" />
<div class="ipsColumns">
  <div class="ipsColumn_fluid">
    <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
      <h4 class="ipsDataItem_title"><strong>Wyszukiwanie przedmiotu</strong></h4><br>
    </div>
    <ul class="ipsDataList ipsBox ipsPad">
      <div class="ipsColumn ipsColumn_wide ipsType_center">
        <form action="" method="POST">
          <label for="item_value">Wartość:</label>
          <input class="ipsField_short" name="item_value" type="text" placeholder="">
          <select name="search_value">
            <option value="uid">UID przedmiotu</option>
            <option value="name">Nazwa przedmiotu</option>
          </select>
          <input class="ipsButton ipsButton_primary ipsButton_verySmall" type="submit" value="Wyszukaj" style="margin-left: 10px;">
        </form>
      </div>
    </ul>
  </div>
  <div style="clear: both"></div>
  {{if $item }}
    <div class="ipsColumn_fluid ipsBox ipsPad" style="margin-top: 10px;">
      <table class="ipsTable ipsTable_responsive" data-role="table">
        <thead>
          <tr class="ipsAreaBackground">	
            <th data-key="ID">
              ID przedmiotu
            </th>
            <th data-key="Nazwa">					
              Nazwa
            </th>	
            <th data-key="Typ właściciela">					
              Typ właściciela
            </th>	
            <th data-key="Właściciel">	
              Właściciel
            </th>           
            <th data-key="Wartość 1">	
              Wartość 1
            </th>
            <th data-key="Wartość 2">	
              Wartość 2
            </th>
          </tr>
        </thead>
        {{foreach $item as $row}}
			<tbody>
              <tr>
                <td>
                  {$row['item_uid']}
                </td>
                <td>
                  {$row['item_name']}
                </td>
                <td>
                  {$row['item_ownertype']}
                </td>
                <td>
                  {$row['item_owner']}
                </td>
                <td>
                  {$row['item_value1']}
                </td>
                <td>
                  {$row['item_value2']}
                </td>
              </tr>
       		</tbody>
        {{endforeach}}
      </table>
    </div>
  {{endif}}
</div>