<ips:template parameters="$tresc" />
<div class="ipsColumns">
  <div class="ipsColumn_fluid">
    {{if !$tresc }}
      {{if !\IPS\Request::i()->search_value }}
      <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
        <h4 class="ipsDataItem_title"><strong>Wybierz czynność</strong></h4><br>
      </div>
      <ul class="ipsDataList ipsBox ipsPad">
        <div class="ipsColumn ipsColumn_wide ipsType_center">

          <form action="" method="GET">
            <input type="hidden" name="app" value="game">
            <input type="hidden" name="module" value="admincp">
            <input type="hidden" name="tab" value="logsGamers">
            Typ logów:
            <select name="search_value">
              <option value="item">Przedmioty</option>
              <option value="login">Logowania</option>
              <option value="chat">Czat</option>
              <option value="pw">Prywatne wiadomości</option>
              <option value="cash">Pieniądze</option>
              <option value="damage">Obrazenia</option>
            </select>
            <input class="ipsButton ipsButton_primary ipsButton_verySmall" type="submit" value="Wybierz" style="margin-left: 10px;">
          </form>
        </div>
      </ul>
     {{else}}
      <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
        <h4 class="ipsDataItem_title"><strong>Wybierz gracza</strong></h4><br>
      </div>
      <ul class="ipsDataList ipsBox ipsPad">
        <div class="ipsColumn ipsColumn_wide ipsType_center">
          <form action="" method="POST">
            <input type="hidden" name="app" value="game">
            <input type="hidden" name="module" value="admincp">
            <input type="hidden" name="tab" value="logsGamers">
            <input type="hidden" name="search_value" value='{expression="\IPS\Request::i()->search_value"}'>
            Typ logów:
            <select name="search_type">
              <option value="1">UID postaci</option>
              <option value="2">Nick postaci</option>
            </select>
            <input type="text" name="value">
            <input class="ipsButton ipsButton_primary ipsButton_verySmall" type="submit" value="Wybierz" style="margin-left: 10px;">
            <a href="/index.php?/admincp/&tab=logsGamers" class="ipsButton ipsButton_negative ipsButton_verySmall">Cofnij</a>
          </form>
        </div>
      </ul>
     {{endif}}
    {{else}}
    	<div class="ipsType_sectionTitle ipsType_reset cForumTitle">
        	<h4 class="ipsDataItem_title"><strong>Wybrane logi</strong></h4>
          <br>
          <div class="ipsType_right" style="margin-top: -25px">
                <a href="/index.php?/admincp/&tab=logsGamers" class="ipsButton ipsButton_negative ipsButton_verySmall ipsType_right">Cofnij</a>
            </div>
      	</div>
    	<div class="ipsBox ipsPad">
            {{foreach $tresc as $row}}
                {$row|raw}<br/>
            {{endforeach}}
        </div>
    {{endif}}
  </div>
  <div style="clear: both"></div>
</div>