<ips:template parameters="$tab, $output" />

<div class='ipsBox ipsBox_transparent ipsAreaBackground' id='elAdminTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elAdminTabContent' data-ipsTabBar-itemSelector='.ipsSideMenu_item' data-ipsTabBar-activeClass='ipsSideMenu_itemActive'>
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_bothSpacing'>
		<div class='ipsColumn ipsColumn_wide'>
			<div class='ipsSideMenu' data-ipsSideMenu>
				<ul class="ipsSideMenu_list">
					<li>
						<a href='?app=game&module=admincp' id='tab_dashboard' class='ipsType_normal ipsSideMenu_item {{if $tab === 'dashboard'}}ipsSideMenu_itemActive{{endif}}' title="{lang="dashboard"}" role="tab" aria-selected="{{if $tab === 'dashboard'}}true{{else}}false{{endif}}">
							<i class='fa fa-dashboard'></i>Dashboard
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=scamers' id='tab_scamers' class='ipsType_normal ipsSideMenu_item {{if $tab === 'scamers'}}ipsSideMenu_itemActive{{endif}}' title="{lang="scamers"}" role="tab" aria-selected="{{if $tab === 'scamers'}}true{{else}}false{{endif}}">
							<i class='fa fa-user-secret'></i>Wykrywacz oszustów
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=characters' id='tab_characters' class='ipsType_normal ipsSideMenu_item {{if $tab === 'characters'}}ipsSideMenu_itemActive{{endif}}' title="Postacie" role="tab" aria-selected="{{if $tab === 'characters'}}true{{else}}false{{endif}}">
							<i class='fa fa-male'></i>Postacie
						</a>
					</li>
                                    
                  	<li>
						<a href='?app=game&module=admincp&tab=groups' id='tab_groups' class='ipsType_normal ipsSideMenu_item {{if $tab === 'groups'}}ipsSideMenu_itemActive{{endif}}' title="Grupy" role="tab" aria-selected="{{if $tab === 'groups'}}true{{else}}false{{endif}}">
							<i class='fa fa-users'></i>Grupy
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=items' id='tab_items' class='ipsType_normal ipsSideMenu_item {{if $tab === 'items'}}ipsSideMenu_itemActive{{endif}}' title="Przedmioty" role="tab" aria-selected="{{if $tab === 'items'}}true{{else}}false{{endif}}">
							<i class='fa fa-bomb'></i>Przedmioty
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=cars' id='tab_cars' class='ipsType_normal ipsSideMenu_item {{if $tab === 'cars'}}ipsSideMenu_itemActive{{endif}}' title="Pojazdy" role="tab" aria-selected="{{if $tab === 'cars'}}true{{else}}false{{endif}}">
							<i class='fa fa-car'></i>Pojazdy
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=doors' id='tab_doors' class='ipsType_normal ipsSideMenu_item {{if $tab === 'doors'}}ipsSideMenu_itemActive{{endif}}' title="Drzwi" role="tab" aria-selected="{{if $tab === 'doors'}}true{{else}}false{{endif}}">
							<i class='fa fa-home'></i>Drzwi
						</a>
					</li>
                  
                  <!-- może kiedyś to udostępnimy
                  	<li>
						<a href='?app=game&module=admincp&tab=objects' id='tab_objects' class='ipsType_normal ipsSideMenu_item {{if $tab === 'objects'}}ipsSideMenu_itemActive{{endif}}' title="Obiekty" role="tab" aria-selected="{{if $tab === 'objects'}}true{{else}}false{{endif}}">
							<i class='fa fa-cube'></i>Obiekty
						</a>
					</li>
                  -->
                  	<li>
						<a href='?app=game&module=admincp&tab=pickups' id='tab_pickups' class='ipsType_normal ipsSideMenu_item {{if $tab === 'pickups'}}ipsSideMenu_itemActive{{endif}}' title="Pickupy" role="tab" aria-selected="{{if $tab === 'pickups'}}true{{else}}false{{endif}}">
							<i class='fa fa-info'></i>Pickup'y
						</a>
					</li>
                  <li>
						<a href='?app=game&module=admincp&tab=admins' id='tab_admins' class='ipsType_normal ipsSideMenu_item {{if $tab === 'admins'}}ipsSideMenu_itemActive{{endif}}' title="Admin" role="tab" aria-selected="{{if $tab === 'admins'}}true{{else}}false{{endif}}">
							<i class='fa fa-tag'></i>Sesje Adminów
						</a>
					</li>
                  <li>
						<a href='?app=game&module=admincp&tab=dziwka' id='tab_dziwka' class='ipsType_normal ipsSideMenu_item {{if $tab === 'dziwka'}}ipsSideMenu_itemActive{{endif}}' title="Dziwki" role="tab" aria-selected="{{if $tab === 'dziwki'}}true{{else}}false{{endif}}">
							<i class='fa fa-tag'></i>Dziwki
						</a>
					</li>
                  
                   	<li>
						<a href='?app=game&module=admincp&tab=salon' id='tab_salon' class='ipsType_normal ipsSideMenu_item {{if $tab === 'salon'}}ipsSideMenu_itemActive{{endif}}' title="Salon" role="tab" aria-selected="{{if $tab === 'salon'}}true{{else}}false{{endif}}">
							<i class='fa fa-taxi'></i>Salon
						</a>
					</li>
                  	<li>
						<a href='?app=game&module=admincp&tab=products' id='tab_products' class='ipsType_normal ipsSideMenu_item {{if $tab === 'products'}}ipsSideMenu_itemActive{{endif}}' title="Produkty" role="tab" aria-selected="{{if $tab === 'products'}}true{{else}}false{{endif}}">
							<i class='fa fa-tag'></i>Produkty
						</a>
					</li>
                   	<li>
						<a href='?app=game&module=admincp&tab=anims' id='tab_anims' class='ipsType_normal ipsSideMenu_item {{if $tab === 'anims'}}ipsSideMenu_itemActive{{endif}}' title="Animacje" role="tab" aria-selected="{{if $tab === 'anims'}}true{{else}}false{{endif}}">
							<i class='fa fa-blind'></i>Animacje
						</a>
					</li>
                      <li>
						<a href='?app=game&module=admincp&tab=uprawnienia' id='tab_uprawnienia' class='ipsType_normal ipsSideMenu_item {{if $tab === 'uprawnienia'}}ipsSideMenu_itemActive{{endif}}' title="Uprawnienia" role="tab" aria-selected="{{if $tab === 'uprawnienia'}}true{{else}}false{{endif}}">
							<i class='fa fa-check-square-o'></i>Uprawnienia ADM
						</a>
					</li>
                      	<li>
						<a href='?app=game&module=admincp&tab=tickets' id='tab_tickets' class='ipsType_normal ipsSideMenu_item {{if $tab === 'tickets'}}ipsSideMenu_itemActive{{endif}}' title="Zgłoszenia" role="tab" aria-selected="{{if $tab === 'tickets'}}true{{else}}false{{endif}}">
							<i class="fa fa-ticket" aria-hidden="true"></i>Zgłoszenia
						</a>
					</li>
                  
                  <hr>
                                    
              
                  
                 
                  
                  
                  
                 
                                  
                  	<li>
						<a href='?app=game&module=admincp&tab=logsGamers' id='tab_logsGamers' class='ipsType_normal ipsSideMenu_item {{if $tab === 'logsGamers'}}ipsSideMenu_itemActive{{endif}}' title="Logi graczy" role="tab" aria-selected="{{if $tab === 'logsGamers'}}true{{else}}false{{endif}}">
							<i class='fa fa-slack'></i>Logi postaci z gry
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=logs' id='tab_logs' class='ipsType_normal ipsSideMenu_item {{if $tab === 'logs'}}ipsSideMenu_itemActive{{endif}}' title="Logi" role="tab" aria-selected="{{if $tab === 'logs'}}true{{else}}false{{endif}}">
							<i class='fa fa-slack'></i>Logi kar z gry
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=weblogs' id='tab_weblogs' class='ipsType_normal ipsSideMenu_item {{if $tab === 'weblogs'}}ipsSideMenu_itemActive{{endif}}' title="Logi" role="tab" aria-selected="{{if $tab === 'weblogs'}}true{{else}}false{{endif}}">
							<i class='fa fa-slack'></i>Logi graczy w panelach
						</a>
					</li>
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=weblogsAdmins' id='tab_weblogsAdmins' class='ipsType_normal ipsSideMenu_item {{if $tab === 'weblogsAdmins'}}ipsSideMenu_itemActive{{endif}}' title="Logi" role="tab" aria-selected="{{if $tab === 'weblogsAdmins'}}true{{else}}false{{endif}}">
							<i class='fa fa-slack'></i>Logi adminów w panelach
						</a>
					</li>
                  
              
                  
                  	<li>
						<a href='?app=game&module=admincp&tab=drugs' id='tab_drugs' class='ipsType_normal ipsSideMenu_item {{if $tab === 'drugs'}}ipsSideMenu_itemActive{{endif}}' title="Narkotyki" role="tab" aria-selected="{{if $tab === 'drugs'}}true{{else}}false{{endif}}">
							<i class="fa fa-smile-o" aria-hidden="true"></i>Narkotyki
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<section id='elAdminTabContent' class='ipsBox ipsPad'>
				<div id="ipsTabs_elAdminTabs_tab_{$tab}_panel" class="ipsTabs_panel" aria-labelledby="tab_{$tab}" aria-hidden="false">
					{$output|raw}
				</div>
			</section>
		</div>
	</div>
</div>