<ips:template parameters="$product" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>  

<div class='ipsType_center ipsPad'>
<a href="index.php?/admincp/&action=productsAddNew" data-ipsdialog data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Dodawanie produktu do hurtowni">
    <span class="ipsButton ipsButton_medium ipsButton_positive">
      Dodaj nowy produkt do hurtowni
    </span>
  </a> 
</div>
<hr class='ipsHr'>
          <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj produktu po nazwie">
  </div>
 <table id="sarpTable">
  <tr class="header">
    <th> </th>
          
          <th  data-key="UID">					
            UID
          </th>	

          <th data-key="locky">	
            Nazwa
          </th>
          
          <th  data-key="CMDo">					
            Kategoria
          </th>	

          <th data-key="lib">	
            Cena
          </th>   

          <th data-key="speed">	
            Typ
          </th>

          <th data-key="loop">	
            Value1
          </th>

          <th data-key="lockx">	
            Value2
          </th>
       <th> </th>
  </tr>
 {{foreach $product as $row}}
        <tr class="ipsClearfix" data-keynavblock="">	
 		<td>
             <a href="index.php?/admincp/&deleteProduct={$row['uid']}" class="ipsType_negative ipsType_normal ipsPos_right ipsFaded ipsFaded_more ipsFaded_withHover" data-ipstooltip="" data-action="disable" _title="Usuń ten produkt" style=""><i class="fa fa-times"></i></a>
          </td>
          <td data-title="UID">	
            <div class="ipsDataItem_title ipsType_light">{$row['uid']}</div>
          </td> 
          
          <td data-title="locky">	
            <div class="ipsDataItem_title">{$row['name']}</div>
          </td> 

          <td data-title="CMDo">
            <div class="ipsDataItem_title ipsType_light">
             <i data-ipstooltip="" _title="Typ grupy: {$row['grouptype']}" class="fa fa-info-circle ipsType_issue"></i>
              {$row['category']}</div>
          </td>

          <td data-title="lib">	
            <div class="ipsDataItem_title ipsType_success">${$row['dealer_cost']}</div>
          </td> 

          <td data-title="speed">	
            <div class="ipsDataItem_title ipsType_light">{$row['type']}</div>
          </td> 

          <td data-title="loop">	
            <div class="ipsDataItem_title ipsType_light">{$row['value1']}</div>
          </td> 

          <td data-title="lockx">	
            <div class="ipsDataItem_title ipsType_light">{$row['value2']}</div>
          </td> 
   </tr>
		{{endforeach}}
</table>

