<ips:template parameters="$scam" />
<div class='ipsMessage ipsMessage_info'>
	Wykres przedstawia najbogatszych graczy na serwerze, sortując od tego który posiada najwięcej gotówki łącznie - przy postaci oraz w banku.<br />
 	Jeśli gracz posiada sporą ilość gotówki a jego czas spędzony w gre jest mizerny, powinieneś poprzeglądać jego logi w zakładce <a href="http://h-rp.eu/index.php?app=game&module=admincp&tab=logsGamers">Logi graczy</a>
</div>

  <script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>   
  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj po nicku OOC">
  </div>
  
  <table id="sarpTable" class='ipsPad'>
  <tr class="header">
    <th>UID</th>
    <th>Global</th>
    <th>Nickname</th>
    <th>Gotówka</th>
    <th>Bank</th>
    <th>Czas online </th>
    <th></th>
  </tr>
{{foreach $scam as $row}}
        <tr class="ipsClearfix" data-keynavblock="">	

          <td data-title="UID">	
            <div class="ipsDataItem_title ipsType_light">{$row['char_uid']}</div>
          </td> 

          <td data-title="CMDo">
            <a href="index.php?/profile/{$row['char_uid']}-redirect">
            <div class="ipsDataItem_title">{$row['char_gid']}</div>
            </a>
          </td>

          <td data-title="lib">	
            <div class="ipsDataItem_title">
              {{if $row['cash'] + $row['char_bankcash'] > $row['char_hours'] * 1500}}
              <div class="ipsDataItem_title ipsType_negative"> 
                  <i data-ipstooltip="" _title="Ten gracz ma za dużo gotówki w stosunku do czasu spędzonego w grze" class="fa fa-circle ipsType_negative"></i>
                {$row['char_name']} 
                {{else}} <div class="ipsDataItem_title ipsType_light"> {$row['imie_nazwisko']}  {{endelse}} {{endif}}
            </div>
          </td> 

          <td data-title="name">	
            <div class="ipsDataItem_title ipsType_light">${$row['cash2']}</div>
          </td> 

          <td data-title="speed">	
            <div class="ipsDataItem_title ipsType_light">${$row['bank2']}</div>
          </td> 

          <td data-title="loop">	
            <div class="ipsDataItem_title ipsType_light">{$row['hours']}h, {$row['minutes']}m</div>
          </td> 
              </tr>
		{{endforeach}}
</table>
