<ips:template parameters="$adminsData" />
<style>
  
  .ipsTable th{padding:2px;}
  </style>
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Uprawnienia</h2>
<hr class="ipsHr">
<div class='ipsMessage ipsMessage_warning'>
	<b> UWAGA! </b> Jeśli nie chcesz nadać ŻADNYCH uprawnień - zaznacz flagę X. <br /> <strong> JEŚLI ZAZNACZASZ <i> X </i> MUSISZ MIEĆ ODZNACZONE WSZYSTKIE INNE FLAGI DLA KONKRETNEGO UŻYTKOWNIKA!
</div>
<div class="ipsBox">
  <table class="ipsTable ipsTable_responsive" data-role="table">
    <thead>
      <tr class="ipsAreaBackground">											
        <th data-key="Nick">					
           <h2 class="ipsType_sectionTitle ipsType_reset">      
              Administrator
           </h2>
        </th>
        <th data-key="Obowiazki" width="10%">					
           <h2 class="ipsType_sectionTitle ipsType_reset">      
              Obowiązki
           </h2>
        </th>
         <th data-ipstooltip="" _title="GM_0" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">GM (OLD)</span>
        </th>
        <th data-ipstooltip="" _title="GM_1" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">GM 1</span>
        </th>	
         <th data-ipstooltip="" _title="GM_2" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">GM 2</span>
        </th>	
         <th data-ipstooltip="" _title="GM_3" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">GM 3</span>
        </th>	
         <th data-ipstooltip="" _title="GM_4" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">GM 4</span>
        </th>	
        <th data-ipstooltip="" _title="SUPP" width="1%"	>
          <span class="ipsBadge ipsBadge_large ipsBadge_new">S</span>
        </th>           
        <th data-ipstooltip="" _title="ROOT" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">RA</span>
        </th>
        <th data-ipstooltip="" _title="Drzwi" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">D</span>
        </th>
        <th data-ipstooltip="" _title="Pojazdy" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">VP</span>
        </th>
        <th data-ipstooltip="" _title="Grupy" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">G</span>
        </th>
        <th data-ipstooltip="" _title="Strefy" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">S</span>
        </th>        
        <th data-ipstooltip="" _title="Obiekty" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">O</span>
        </th>
         <th data-ipstooltip="" _title="Przedmioty" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_new">P</span>
        </th>
        <th data-ipstooltip="" _title="Odebrane" width="1%">	
          <span class="ipsBadge ipsBadge_large ipsBadge_negative">X</span>
        </th>
      </tr>
    </thead>
    <form action="" method="POST">
    {{foreach $adminsData as $row}}
    <tbody>
      <tr class="ipsClearfix">
        <td style="padding: 15px">
          <h3 class="ipsType_sectionHead" style="margin-right: 5px">
            {expression="\IPS\Member\Group::load( $row['member_group_id'] )->formatName ( $row['name'] ) " raw="true"}
          </h3>
        </td>
        <td>
           	<input type="text" name="duties[{$row['member_id']}]" value="{$row['admin_obowiazki']}">
        </td>
        <td><input name="perm[{$row['member_id']}][1]" type="checkbox" {{if $row['member_game_admin_perm'] & 1}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][512]" type="checkbox" {{if $row['member_game_admin_perm'] & 512}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][1024]" type="checkbox" {{if $row['member_game_admin_perm'] & 1024}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][2048]" type="checkbox" {{if $row['member_game_admin_perm'] & 2048}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][4096]" type="checkbox" {{if $row['member_game_admin_perm'] & 4096}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][2]" type="checkbox" {{if $row['member_game_admin_perm'] & 2}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][4]" type="checkbox" {{if $row['member_game_admin_perm'] & 4}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][8]" type="checkbox" {{if $row['member_game_admin_perm'] & 8}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][16]" type="checkbox" {{if $row['member_game_admin_perm'] & 16}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][32]" type="checkbox" {{if $row['member_game_admin_perm'] & 32}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][64]" type="checkbox" {{if $row['member_game_admin_perm'] & 64}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][128]" type="checkbox" {{if $row['member_game_admin_perm'] & 128}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][256]" type="checkbox" {{if $row['member_game_admin_perm'] & 256}}checked{{endif}}></td>
        <td><input name="perm[{$row['member_id']}][0]" type="checkbox" {{if $row['member_game_admin_perm'] == 0}}checked{{endif}}></td>
      </tr>
    </tbody>
    {{endforeach}}
      <tbody>
        <tr>
          <td colspan="8" style="text-align: center">
     		 <input class="ipsButton ipsButton_primary"type="submit" value="Zapisz">
          </td>
        </tr>
      </tbody>
    </form>
  </table>
</div>