<ips:template parameters="$weblogs" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>   

  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj wpis po koncie globalnym">
  </div>

 <table id="sarpTable" class='ipsPad'>
  <tr class="header">
    <th>ID</th>
    <th>Global OOC</th>
    <th>Postać ID</th>
    <th>Typ logu</th>
    <th>Wartość 1</th>
    <th>Wartość 2</th>
    <th>Data</th>
  </tr>
  {{foreach $weblogs as $row}}
    	<tr>
          <td>
            {$row['id']}
          </td>
          <td>
            <a href="http://h-rp.eu/index.php?/profile/{$row['user_gid']}-redirect/" data-ipshover="" data-ipshover-target="http://H-RP.EU/index.php?/profile/{$row['user_gid']}-redirect/&do=hovercard" class="ipsUserPhoto ipsUserPhoto_tiny">
                  <img src="{$row['photo']}">
                </a>
            {$row['user_gid2']}
          </td>
          <td>
            {$row['char_id']}
          </td>
          <td>
            {$row['type']}
          </td>
          <td>
            {$row['action_1']}
          </td>
          <td>
            {$row['action_2']}
          </td>
          <td>
            {datetime="$row['date']"}
          </td>
      </tr>
  {{endforeach}}
</table>

