<ips:template parameters="$charData" />
<div class="ipsColumns ipsColumns_bothSpacing ipsColumns_halfSpacing ipsPad">
  <div class="ipsColumn ipsColumn_wide ipsBox ipsPad">
    <h1 class="ipsType_sectionTitle ipsType_issue"><strong>Informacje</strong></h1>
    <hr class="ipsHr">
    <ul class="ipsDataList">

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Global</strong></h4><br>
          <div class="">
            <a href="https://h-rp.eu/index.php?/profile/{$charData['gid']}-redirect/" data-ipshover="" data-ipshover-target="https://h-rp.eu/index.php?/profile/{$charData['gid']}-redirect/&do=hovercard" class="ipsUserPhoto ipsUserPhoto_tiny">
              <img src="{$charData['photo']}">
            </a> 
            <a href="https://h-rp.eu/index.php?/profile/{$charData['gid']}-redirect/" data-ipshover="" data-ipshover-target="https://h-rp.eu/index.php?/profile/{$charData['gid']}-redirect/&do=hovercard">
              {$charData['gid2']}
            </a>
            (GID: {$charData['gid']})</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Dane postaci</strong></h4><br>
          <div class="">{$charData['imie_nazwisko2']} (ID: {$charData['id']})</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Status postaci</strong></h4><br>
          <div class="">
            {{if $charData['block'] == 0 }}
            <span class="ipsType_success"> Aktywna </span>
            {{else}}
            <span class="ipsType_negative"> Zablokowana </span> 
            {{endif}}
          </div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Widoczność</strong></h4><br>
          <div class="">
            {{if $charData['ukryta'] == 0 }}
            <span class="ipsType_success"> Widoczna </span>
            {{else}}
            <span class="ipsType_negative"> Ukryta </span> 
            {{endif}}
          </div>
        </div>
      </li>


      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>AJ</strong></h4><br>
          <div class="">{$charData['aj']} min</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Ostatnio w grze</strong></h4><br>
          <div class="">{datetime="$charData['last']"}</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Dziś w grze</strong></h4><br>
          <div class="">{$charData['today']} min</div>
        </div>
      </li>

      <hr class="ipsCommentUnreadSeperator">

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Przegrany czas</strong></h4><br>
          <div class="">{$charData['hours']}h, {$charData['minutes']}min </div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Gotówka przy postaci</strong></h4><br>
          <div class="">${$charData['cash']}</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Gotówka w banku</strong></h4><br>
          <div class="">${$charData['bank']}</div>
        </div>
      </li>


      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Siła</strong></h4><br>
          <div class="">{$charData['strength']}j</div>
        </div>
      </li>


      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Konto bankowe</strong></h4><br>
          <div class="">{$charData['account']}</div>
        </div>
      </li>

      <li class="ipsDataItem">
        <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
          <h4 class="ipsDataItem_title"><strong>Hash maski</strong></h4><br>
          <div class="">Nieznajomy_<strong>{expression="substr(md5($charData['id']), 0, 5)"}</strong></div>
        </div>
      </li>

    </ul>
  </div>
  <div class="ipsColumn ipsColumn_fluid ipsBox ipsPad">
    <h1 class="ipsType_sectionTitle ipsType_success"><strong>Zarządzanie {$charData['imie_nazwisko2']}</strong>
      
      <div class="ipsType_right" style="margin-top: -20px; margin-left: 245px;">
        <a href="#nadajkare" class="ipsButton ipsButton_negative ipsButton_verySmall" data-ipsdialog="#nadajkare" data-ipsDialog-content="#nadajkare"  data-ipsdialog-modal="true" data-ipsdialog-size="narrow" data-ipsdialog-title="Nadawanie kary - {$charData['imie_nazwisko2']}">
          <i class="fa fa-ban"></i>&nbsp;<span class="ipsResponsive_hidePhone ipsResponsive_inline">&nbsp;&nbsp;Nadaj karę</span>
        </a>
        
        <a href="#nadajGS" class="ipsButton ipsButton_positive ipsButton_verySmall" data-ipsdialog="#nadajkare" data-ipsDialog-content="#nadajGS"  data-ipsdialog-modal="true" data-ipsdialog-size="narrow" data-ipsdialog-title="Nadawanie GS - {$charData['imie_nazwisko2']}">
          <i class="fa fa-plus"></i>&nbsp;<span class="ipsResponsive_hidePhone ipsResponsive_inline">&nbsp;&nbsp;Nadaj GameScore</span>
        </a>	
      </div>

      <div id='nadajkare' class='ipsHide ipsPad'>
        <form action="" method="POST" class="ipsForm ipsForm_horizontal ">
          <ul class="ipsDataList ipsType_center">

            <li class='ipsFieldRow'>
              <label for='example' class='ipsFieldRow_label'>
                Typ kary
              </label>
              <div class='ipsFieldRow_content'>
                <select name="type">
                  <option value="3">Ban SA-MP</option>
                </select>
                <br />
                <span class='ipsFieldRow_desc'>Wybierz typ kary</span>
              </div>
            </li>
            
              <hr class="ipsHr">
            
            <li class='ipsFieldRow'>
            <label for='example' class='ipsFieldRow_label'>
              Data wygaśnięcia
            </label>
            <div class='ipsFieldRow_content'>
              <input name="expire" type="text"><br />
              <span class='ipsFieldRow_desc'>Określ w dniach kiedy kara wygasa</span><br />
              <span class='ipsFieldRow_desc ipsType_negative'>Jeśli kara ma nigdy nie wygasać wpisz -1</span>
            </div>
          </li>
            
             <hr class="ipsHr">
            
                    <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Powód
          </label>
          <div class='ipsFieldRow_content'>
            <input name="reason" type="text" value=""><br />
            <span class='ipsFieldRow_desc'>Określ powód kary - BEZ POLSKICH ZNAKÓW!</span>
          </div>
        </li>
              <hr class="ipsHr">
             <input type="submit" value="Nadaj karę dla postaci {$charData['imie_nazwisko2']}" class="ipsButton ipsButton_primary ipsButton_small">
          </ul>
          
        </form>
      </div>
      
       <div id='nadajGS' class='ipsHide ipsPad'>
        <form action="" method="POST" class="ipsForm ipsForm_horizontal ">
          <ul class="ipsDataList ipsType_center">
            
         <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Powód
          </label>
          <div class='ipsFieldRow_content'>
            <input name="reason" type="text" value=""><br />
            <span class='ipsFieldRow_desc'>Określ powód nadania punktów - BEZ POLSKICH ZNAKÓW!</span>
          </div>
        </li>
            
            <hr class="ipsHr">
            
          <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Ilość GS
          </label>
          <div class='ipsFieldRow_content'>
            <input name="value" type="text" value=""><br />
            <span class='ipsFieldRow_desc'>Określ ile punktów GS nadajesz</span>
          </div>
        </li>
              <hr class="ipsHr">
             <input type="submit" value="Nadaj GS dla postaci {$charData['imie_nazwisko2']}" class="ipsButton ipsButton_positive ipsButton_small">
          </ul>
          
        </form>
      </div>

    </h1>
    <hr class="ipsHr">
    <ul class="ipsDataList ipsType_center">

      <form action="" method="POST" class="ipsForm ipsForm_horizontal ">

        <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Imię i nazwisko
          </label>
          <div class='ipsFieldRow_content'>
            <input name="nickname" type="text" value="{$charData['imie_nazwisko']}"><br />
            <span class='ipsFieldRow_desc'>Nickname określ formatem Imie_Nazwisko</span>
          </div>
        </li>

        <hr class="ipsHr">

        <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Punkty życia
          </label>
          <div class='ipsFieldRow_content'>
            <input name="health" type="text" value="{$charData['health']}"><br />
            <span class='ipsFieldRow_desc'>Określ w przedziale 1-100 życie postaci</span>
          </div>
        </li>

        <hr class="ipsHr">

        <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Skin
          </label>
          <div class='ipsFieldRow_content'>
            <input name="skin" type="text" value="{$charData['skin']}"><br />
            <span class='ipsFieldRow_desc'>Określ skin postaci od 1 do 10000</span>
          </div>
        </li>

        <hr class="ipsHr">

        <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Wiek
          </label>
          <div class='ipsFieldRow_content'>
            <input name="age" type="text" value="{$charData['age']}"><br />
            <span class='ipsFieldRow_desc'>Określ wiek postaci od 1 do 100</span>
          </div>
        </li>

        <hr class="ipsHr">

        <li class='ipsFieldRow'>
          <label for='example' class='ipsFieldRow_label'>
            Płeć
          </label>
          <div class='ipsFieldRow_content'>
            <select name="sex">
              <option {{if $charData['sex'] == 1}} selected {{endif}} value="1">Mężczyzna</option>
              <option {{if $charData['sex'] == 2}} selected {{endif}}value="2">Kobieta</option>
            </select>
            <br />
            <span class='ipsFieldRow_desc'>Zmiana płci postaci</span>
          </div>
        </li>

        <hr class="ipsCommentUnreadSeperator">

        <div class='ipsFieldRow_content '>

          <li class='ipsFieldRow'>
            <label for='example' class='ipsFieldRow_label'>
              Adminjail
            </label>
            <div class='ipsFieldRow_content'>
              <input size='5' name="aj" type="text" value="{$charData['aj']}"><br />
              <span class='ipsFieldRow_desc'>Określ adminjail w minutach / 0 oznacza brak AJ</span>
            </div>
          </li>

          <hr class="ipsHr">

          <li class='ipsFieldRow'>
            <label for='example' class='ipsFieldRow_label'>
              Blokada postaci
            </label>
            <div class='ipsFieldRow_content'>
              <select name="block">
                <option {{if $charData['char_active'] == 0}} selected {{endif}} value="0">Postać odblokowana</option>
                <option {{if $charData['char_active'] == 1}} selected {{endif}}value="1">Postać zablokowana</option>
              </select>
              <br />
              <span class='ipsFieldRow_desc ipsType_warning'>Jeśli postać została zablokowana w grze lub poprzez panel (widać wpis w logach), odblokuj ją poprzez panel <a href="/index.php?app=game&module=admincp&tab=logs">logów kar</a>!!!</span>
            </div>
          </li>

          <hr class="ipsHr">

          <li class='ipsFieldRow'>
            <label for='example' class='ipsFieldRow_label'>
              Widoczność postaci
            </label>
            <div class='ipsFieldRow_content'>
              <select name="visible">
                <option {{if $charData['char_visible'] == 0}} selected {{endif}} value="0">Postać widoczna</option>
                <option {{if $charData['char_visible'] == 1}} selected {{endif}} value="1">Postać ukryta</option>
              </select>
              <br />
              <span class='ipsFieldRow_desc'>Określenie widoczności postaci w profilu</span>
            </div>
          </li>
        </div>
        <br />
        <div style="text-align: center">
          <input type="submit" value="Zapisz postać {$charData['imie_nazwisko2']}" class="ipsButton ipsButton_primary ipsButton_small">
        </div>
      </form>

    </ul>
  </div>
</div>
<a href="/index.php?app=game&module=admincp&tab=characters"><div class="ipsPad ipsButton ipsButton_normal ipsButton_fullWidth ipsType_sectionTitle"> <strong><< Powrót do list postaci </strong></div></a><br />