<ips:template parameters="$characterData, $characterGroups,$characterItems, $characterCars, $characterDoors" />
<script>
  function switchTabs(chosen)
  {
    $(".saCharacterTab").hide();
    $(".tab_"+chosen).show();
    $('.href_tab_'+chosen).addClass('ipsSideMenu_itemActive');
    $('.saCharacterHref').removeClass('ipsSideMenu_itemActive');
    $('.href_tab_'+chosen).addClass('ipsSideMenu_itemActive');
  }
</script>
<style>
  .ipsType_sectionTitle{background:none;}
  .ipsDialog.ipsDialog_medium > div{max-width:1050px;}
  .saCharacter{border:none; box-shadow:none;}
</style>
{{if $characterData['char_gid'] == \IPS\Member::loggedIn()->member_id OR \IPS\Member::loggedIn()->isAdmin()}}
<div style="position: absolute; right: 55px; font-size: 18px; top: 10px;">

  {{if $characterData['char_visible'] == 0}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&hidden=0" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Ukryj postać
  </a>
  {{else}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&hidden=1" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Odkryj postać
  </a>
  {{endif}}
  {{if  \IPS\game\Character::isAdminRoot( \IPS\Member::loggedIn()->member_id)}}
    {{if $characterData['char_active'] == 0}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&active=1" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Zablokuj postać
  </a>
  {{else}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&active=0" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Odblokuj postać
  </a>
  {{endif}}
   {{if !\IPS\game\Character::isBanPlayer($characterData['char_gid']) }}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&member={$characterData['char_gid']}&ban=0" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Odblokuj dostęp do gry
  </a>
  {{else}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&member={$characterData['char_gid']}&ban=1" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Zablokuj dostęp do gry
  </a>
  {{endif}}
      {{if $characterData['char_aj'] != 0}}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&AdminJail=0" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Sciągnij AdminJail
  </a>
  {{endif}}
     {{if \IPS\game\Character::isTBanPlayer($characterData['char_gid']) }}
  <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&member={$characterData['char_gid']}&Tban=0" class="ipsButton ipsButton_veryLight ipsButton_small" style="font-size: 16px;">
    <i class="fa fa-eye" aria-hidden="true"></i> Ściąg bana czasowego (TBAN)
  </a>
  {{endif}}
  {{endif}}
</div>
<div id='remove' class='ipsHide ipsPad'>
  <div class='ipsMessage ipsMessage_error'>
  <p>Czy jesteś pewien, że chcesz usunąć postać {$characterData['imie_nazwisko']}? </p>
    <p><strong>Akcja nie będzie mogła być już cofnięta!</strong></p>
</div>
  <hr class='ipsHr'>

</div>
{{endif}}
<div class="ipsColumns ipsColumns_collapsePhone ipsColumns_bothSpacing">
  <div class="ipsColumn ipsColumn_wide saSideMenu">
    <div class="ipsSideMenu">
      <ul class="ipsSideMenu_list">
        <li>
          <a onClick="switchTabs(1)" class="href_tab_1 saCharacterHref ipsType_normal ipsSideMenu_item ipsSideMenu_itemActive" title="Podsumowanie">
            <i class="fa fa-vcard fa-lg"></i>&nbsp;Podsumowanie
          </a>
        </li>
        {{if $characterData['char_gid'] == \IPS\Member::loggedIn()->member_id OR \IPS\Member::loggedIn()->isAdmin()}}
        <li>
          <a onClick="switchTabs(2)" class="href_tab_2 saCharacterHref ipsType_normal ipsSideMenu_item" title="Grupy">
            <i class="fa fa-users fa-lg"></i>&nbsp; Grupy
          </a>
        </li>
        <li>
          <a onClick="switchTabs(3)" class="href_tab_3 saCharacterHref ipsType_normal ipsSideMenu_item" title="Przedmioty">
            <i class="fa fa-cubes fa-lg"></i>&nbsp; Przedmioty
          </a>
        </li>
        <li>
          <a onClick="switchTabs(4)" class="href_tab_4 saCharacterHref ipsType_normal ipsSideMenu_item" title="Pojazdy">
            <i class="fa fa-car fa-lg"></i>&nbsp; Pojazdy
          </a>
        </li>
        <li>
          <a onClick="switchTabs(5)" class="href_tab_5 saCharacterHref ipsType_normal ipsSideMenu_item" title="Posiadłości">
            <i class="fa fa-home fa-lg"></i>&nbsp; Posiadłości
          </a>
        </li>        
        <li>
          <a onClick="switchTabs(6)" class="href_tab_6 saCharacterHref ipsType_normal ipsSideMenu_item" title="Posiadłości">
            <i class="fa fa-hashtag fa-lg"></i>&nbsp; Sesje logowań
          </a>
        </li>
        {{endif}}
      </ul>
    </div>
  </div>
  <div class="saCharacterTab ipsColumn_fluid tab_1" style="display: block; top: -20px">
    {{if $characterData['char_gid'] != \IPS\Member::loggedIn()->member_id && !\IPS\Member::loggedIn()->isAdmin()}}
    <div class='ipsBox ipsPad'>
      <div class='ipsMessage ipsMessage_error'>
        <span class='ipsMessage_code'>ANTY-RYCIE-W-KODZIE</span>
        Ups, postać którą próbujesz wyświetlić jest ukryta i nie należy do Ciebie :(
      </div>
    </div>
    {{else}}
    <h4 class="ipsType_light ipsType_medium">
      {{if $characterData['char_visible'] == 1 && $characterData['char_active'] == 1}}
      <span class="ipsBadge ipsBadge_large ipsBadge_negative"><strong> <i class="fa fa-ban fa-lg"></i>&nbsp; Postać zablokowana</strong></span>
      {{elseif $characterData['char_visible'] == 1}}
      <span class="ipsBadge ipsBadge_large ipsBadge_warning"><strong> <i class="fa fa-eye fa-lg"></i>&nbsp; Postać ukryta</strong></span>
      {{endelseif}}
      {{elseif $characterData['char_active'] == 1}}
      <span class="ipsBadge ipsBadge_large ipsBadge_negative"><strong> <i class="fa fa-ban fa-lg"></i>&nbsp; Postać zablokowana</strong></span>
      {{endelseif}}
      {{endif}}
      <span class="ipsBadge ipsBadge_large ipsBadge_new"><strong> UID postaci: </strong>{$characterData['uid']}</span>
      {{if $characterData['czy_online'] == 1}}
      <span class="ipsBadge ipsBadge_large ipsBadge_positive"><strong> <i class="fa fa-gamepad fa-lg"></i>&nbsp; Aktualnie online</strong></span>
      {{else}}
      <span class="ipsBadge ipsBadge_large ipsBadge_new"><strong> <i class="fa fa-clock-o fa-lg"></i>&nbsp; Ostatnie logowanie</strong> - {{if $characterData['player_last_join'] == 0}} nigdy nie logowano {{else}} {datetime="$characterData['player_last_join']"} {{endelse}} {{endif}}</span>
      {{endelse}}
      {{endif}} 
    </h4>
    <section id="elProfileTabContent" class="ipsBox ipsPad">  
      <div class='ipsColumns hrpshow'>
        <div class='ipsColumn ipsColumn_wide'>
          <ul class="ipsDataList">
           <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Imie i nazwisko</strong></h4><br>
                <div class="ipsOnlineStatus_offline">{{if $characterData['char_visible'] == 0}}{$characterData['name']}{{else}} Postać Ukryta{{endif}}</div>
              </div>
            </li>
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Płeć</strong></h4><br>
                {{if $characterData['gender'] == 1}}
                <div class="ipsOnlineStatus_offline">Mężczyzna</div>
                {{else}}
                <div class="ipsOnlineStatus_offline">Kobieta</div>
                {{endelse}}
                {{endif}}
                </li>
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Data urodzenia</strong></h4><br>
                <div class="ipsOnlineStatus_offline">{$characterData['char_birth']}</div>
              </div>
            </li> 
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Przegrany czas</strong></h4><br>
                <div class="ipsOnlineStatus_offline">{$characterData['online_hours']}h {$characterData['online_minutes']}min</div>
              </div>
            </li> 
            
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Dziś w grze</strong></h4><br>
                <div class="ipsOnlineStatus_offline">{datetime="$characterData['player_last_join']"}</div>
              </div>
            </li> 
             <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Tatuaże</strong></h4><br>
                <div class="ipsOnlineStatus_offline">{$characterData['player_tatto']}</div>
              </div>
            </li> 
          </ul>
        </div>
        {{if $characterData['char_gid'] == \IPS\Member::loggedIn()->member_id}}
        <div class='ipsColumn'>
          <div class="ipsColumn ipsColumn_fixed ipsColumn_veryWide" id="elProfileInfoColumn">
            <ul class="ipsDataList">
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Stan zdrowia</strong></h4><br>
                  <div class="ipsType_negative">{$characterData['health']}%</div>
                </div>
              </li>
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Gotówka</strong></h4><br>
                  <div class="ipsType_positive"><strong>$</strong> {$characterData['cash']} </div>
                </div>
              </li>
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Stan konta</strong></h4><br>
                  <div class="ipsType_positive"><strong>$</strong> {$characterData['bankcash']} </div>
                </div>
              </li>
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Aktualny Spawn</strong></h4><br>
                  <div class="ipsType_positive"><strong>
                    
                    
                    <a href="">{{if $characterData['char_spawn_type'] == 1}}
                  
                     <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&spawn=0" title="Zmień spawn na Las Barancas" style="font-size: 19px; color:#598f5b;">
                       Fort Carson  <i class="fas fa-exchange-alt"></i>
                      
                      </a>
                      {{endif}}
                      {{if $characterData['char_spawn_type'] == 2}}
                      <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&spawn=1" title="Zmień spawn na Fort Carson" style="font-size: 19px; color:#598f5b;">
                      Las Barancas  <i class="fas fa-exchange-alt"></i>
                      </a>
                      {{endif}} 
                      {{if $characterData['char_spawn_type'] != 2 &&  $characterData['char_spawn_type'] != 1}}
                      Budynek
                      {{endif}}
                   
                   
                      
                      </a></strong></div>
                </div>
              </li>
<li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Reset pozycji <br>(w przypadku CRASHY)</strong></h4><br>
                  <div class="ipsType_negative"><strong>
                    
                    
                   
                  <span class="ipsBadge ipsBadge_large ipsBadge_negative"><strong> <i class="fa fa-ban fa-lg"></i>&nbsp; <a href="https://h-rp.eu/index.php?app=game&module=character&controller=character&hide={$characterData['uid']}&reset=0" title="Zresetuj pozycje" style=" color:#fff;">
                    Resetuj pozycje </a></strong></span>
                
                      
                      
                       
                      
                      
                     
                      
                      
                      
                     </strong></div>
                </div>
              </li>
            </ul>
          </div>
        </div>  
        {{endif}}
        <div> 
          <div style="float: right; margin-left: 25px; margin-top: 35px " class="saCharacter">
            {{if $characterData['skin'] > 300}}<img src="https://wynalazca.tv/wp-content/uploads/2017/09/pytajnik-wynalazek-patent-min.png">   <br/>{{else}} {{if $characterData['char_visible'] == 1}}{{else}}<img src="https://h-rp.eu/images/skins/{$characterData['skin']}.png">{{endif}}   <br/>{{endif}}
          </div>
        </div>
      </div>
      <div style="clear: both"></div>
    </section>
    {{endelse}}
    {{endif}}
  </div>
  {{if $characterData['char_gid'] == \IPS\Member::loggedIn()->member_id OR \IPS\Member::loggedIn()->isAdmin()}}
  <div class="saCharacterTab ipsColumn_fluid tab_2">
    {{if !$characterGroups}}
    <div class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_warning'>
        Twoja postać to nierób bo nigdzie nie pracuje :)
      </div>
    </div>
    {{else}}
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_info'>
        Wszystkie grupy do, których należy Twoja postać.
      </div>

      <table id="sarpTable">
        <tr class="header">
          <th  data-key="Grupa">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Grupa</strong></h5></div>
          </th>         
          <th  data-key="Ubranie">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Ubranie</strong></h5></div>
          </th>         
          <th  data-key="Wypłata">  
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Wypłata</strong></h5></div>
          </th>
          <th data-key="Czas duty"> 
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Czas duty</strong></h5></div>
          </th>
          <th></th>
        </tr>
        {{foreach $characterGroups as $row}}
        <tr class="ipsClearfix" data-keynavblock="">  
          <td class=" ipsTable_wrap ipsTable_primary "> 
            <a href="https://h-rp.eu/index.php?app=game&module=group&char_id={$row['char_uid']}&group_id={$row['group_belongs']}"><div class="ipsDataItem_title">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['imie_nazwisko']}</h5></div>
              </div></a>
          </td>
          <td data-title="skin">
            <div style="border: 1px #ddd solid; float: left; padding: 2px; border-radius: 2px; margin: 2px;">
               {{if $row['group_skin'] > 300 || $row['group_skin'] == 1}}<img src="https://h-rp.eu/images/skins/unknow.png">   <br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['group_skin']}.png">   <br/>{{endif}}
            </div>
          </td>     
          <td class=" ipsTable_primary" data-title="wyplata">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">$ {$row['group_payment']}</h5></div>
          </td>
          <td data-title="duty">
            {{if $row['group_time'] >= 10}}
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <i data-ipstooltip="" _title="Pamiętaj, aby dostać wypłatę musisz przepracować 30 minut!" class="fa fa-check-circle ipsType_positive"></i>
              <h5 class="ipsDataItem_title ipsType_positive">{$row['group_time']} min</h5></div>       
            {{else}}    
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <i data-ipstooltip="" _title="Nie kwalifikuje się do wypłaty" class="fa fa-times-circle ipsType_negative"></i>
              <h5 class="ipsDataItem_title ipsType_negative">{$row['group_time']} min</h5></div>

            {{endelse}} {{endif}}
          </td> 
        </tr>
        {{endforeach}}
      </table>

    </section>
    {{endelse}}
    {{endif}}
  </div>
  <div class="saCharacterTab ipsColumn_fluid tab_3">
    {{if !$characterItems}}
    <div class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_warning'>
        Postać nie posiada żadnych przedmiotów.
      </div>
    </div>
    {{else}}
    <section id="elProfileTabContent" class="ipsBox ipsPad">

      <table id="sarpTable">
        <tr class="header">
          <th  data-key="UID">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>UID</strong></h5></div>
          </th>         
          <th  data-key="Nazwa">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Nazwa</strong></h5></div>
          </th>         
          <th  data-key=">Wartość 1"> 
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Wartość 1</strong></h5></div>
          </th>
          <th data-key=">Wartość 2">  
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Wartość 2</strong></h5></div>
          </th>
          <th></th>
        </tr>
        {{foreach $characterItems as $row}}
        <tr class="ipsClearfix" data-keynavblock="">  
          <td  data-title="UID">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['item_uid']}</h5></div>
          </td>
          <td data-title="Nazwa">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              {{if $row['item_extraid'] > 0}}
              <i data-ipstooltip="" _title="Ten przedmiot jest oflagowany dla grupy SAPD." class="fa fa-flag ipsType_negative"></i>
              {{endif}}
              <h5 class="ipsDataItem_title">{$row['item_name']}</h5></div>
          </td>     
          <td class=" ipsTable_primary" data-title="V1">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['item_value1']}</h5></div>
          </td>
          <td data-title="V2">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['item_value2']}</h5></div>
          </td>
        </tr>
        {{endforeach}}
      </table>

    </section>
    {{endelse}}
    {{endif}}
  </div>
  <div class="saCharacterTab ipsColumn_fluid tab_4">
    {{if !$characterCars}}
    <div class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_warning'>
        Postać nie posiada żadnych pojazdów.
      </div>
    </div>
    {{else}}
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      <table id="sarpTable" class='ipsPad'>
        <tr class="header">
          <th  data-key="UID">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>UID</strong></h5></div>
          </th>         
          <th  data-key="Model">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Model</strong></h5></div>
          </th>         
          <th  data-key="HP"> 
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>HP</strong></h5></div>
          </th>
         <th  data-key="Naprawy"> 
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Naprawy</strong></h5></div>
          </th>
          <th data-key="Przebieg">  
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Przebieg</strong></h5></div>
          </th>
          <th data-key="Paliwo">  
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Paliwo</strong></h5></div>
          </th>

          <th></th>
        </tr>
        {{foreach $characterCars as $row}}
        <tbody data-role="tableRows">
          <tr class="ipsClearfix" data-keynavblock="">  
            <td class="ipsTable_primary ipsType_light"> 
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['vehicle_uid']}</h5></div>
            </td>
            <td data-title="Model">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><img src="https://www.rpg3.b-zone.ro/public/img/Vehicles/{$row['vehicle_model']}.png" width="68px" /></h5></div>
            </td>     
            <td class="ipsTable_primary" data-title="HP">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['vehicle_health']} hp</h5></div>
            </td>
            <td class="ipsTable_primary" data-title="Naprawy">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['vehicle_repairs']} hp (MAX: 15.000)</h5></div>
            </td>
            <td data-title="Przebieg">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['vehicle_mileage']}km</h5></div>
            </td>
            <td data-title="Paliwo">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['vehicle_fuel']} L</h5></div>
            </td>
           <td data-title="Szczegóły">
             <!-- <li id="sarpCarsMore" class="ipsCursor_pointer ipsResponsive_showDesktop ipsResponsive_block" data-ipsmenu="" style="">
                <a href='#' class='ipsButton ipsButton_verySmall ipsButton_link'>Zobacz więcej</a>
              </li> -->
              <ul id="sarpCarsMore_menu" class="ipsMenu ipsMenu_narrow ipsHide ipsMenu_bottomCenter" animating="false">
               <li class="ipsMenu_item">
                 <h5 class="ipsDataItem_title ipsType_sectionTitle ipsType_reset cForumTitle"><b>Brak szczegółów</b></h5>
                </li>
                <li class="ipsMenu_item"><span><i class="fa" style="min-width: 30px; top: 15px;">
                  <div  data-ipstooltip="" _title="{$row['vehicle_color1']}" style="border: 1px #ddd solid; border-radius: 2px; width: 20px; height: 20px; background-color: rgb({$row['vehicle_color1']})">                 
                  </div></i>
                  <h5 class="ipsDataItem_title ipsType_sectionTitle ipsType_reset cForumTitle"><b>Kolor pierwszy</b></h5>
                  </span></li>
                <li class="ipsMenu_sep"><hr></li>
                <li class="ipsMenu_item"><span><i class="fa" style="min-width: 30px; top: 15px;">
                  <div  data-ipstooltip="" _title="{$row['vehicle_color2']}" style="border: 1px #ddd solid; border-radius: 2px; width: 20px; height: 20px; background-color: rgb({$row['vehicle_color2']})">                 
                  </div></i>
                  <h5 class="ipsDataItem_title ipsType_sectionTitle ipsType_reset cForumTitle"><b>Kolor drugi</b></h5>
                  </span></li>
           
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Alarm</span></li>
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Immobiliser</span></li>
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Audio</span></li> -->
              </ul>

            </td>
          </tr>
        </tbody>
        {{endforeach}}
      </table>

    </section>
    {{endelse}}
    {{endif}}
  </div>
  <div class="saCharacterTab ipsColumn_fluid tab_5">
    {{if !$characterDoors}}
    <div class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_warning'>
        Postać nie posiada żadnych posiadłości.
      </div>
    </div>
    {{else}}
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_info'>
       Pamietaj, że są to nieruchomości przypisane do Twojej postaci a nie do których masz uprawnienia!
      </div>

      <table id="sarpTable">
        <tr class="header">
          <th  data-key="UID">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>UID</strong></h5></div>
          </th> 
          <th  data-key="Nazwa">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Nazwa</strong></h5></div>
          </th>      
          <th  data-key="Gotówka">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Meble</strong></h5></div>
          </th>   
          <th  data-key="Podatek">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Podatek opłacony do</strong></h5></div>
          </th>   
               <th  data-key="Pickup">          
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Pickup</strong></h5></div>
          </th>  
          <th data-key="Status">  
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Status drzwi</strong></h5></div>
          </th>
          <th></th>
        </tr>
        {{foreach $characterDoors as $row}}
        <tbody data-role="tableRows">
          <tr class="ipsClearfix" data-keynavblock="">  
            <td data-title="ID">  
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['door_uid']}</h5></div>
            </td>
            <td data-title="Nazwa">
              <a href="/index.php?app=game&module=possessions&char_id={$characterData['id']}&possession_id={$row['id']}"><div class="ipsDataItem_title">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">{$row['door_name']}</h5></div>
                </div></a>  
            </td>       
            <td data-title="Gotówka">
             <div class="ipsDataItem_title">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">{$row['door_objects']}</h5></div>
                </div>  
            </td> 
            <td data-title="Podatek">
              <a href="/index.php?app=game&module=possessions&char_id={$characterData['id']}&possession_id={$row['id']}"><div class="ipsDataItem_title">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">{{if $row['door_time_tax'] == 0}} nigdy nie opłacono {{else}} {datetime="$row['door_time_tax']"} {{endelse}} {{endif}}</h5></div>
                </div></a>  
            </td> 
             <td data-title="Pickup">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><img src="https://files.prineside.com/gtasa_samp_model_id/white/{$row['door_pickupid']}_w_s.jpg" width="68px" /></h5></div>
            </td>   
            <td data-title="Status">
              {{if $row['door_lock'] == 1}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><i data-ipstooltip="" _title="Drzwi zamkniete" class="fa fa-lock ipsType_negative"></i>&nbsp;Zamknięte</h5></div>
              {{else}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><i data-ipstooltip="" _title="Drzwi zamkniete" class="fa fa-lock ipsType_positive"></i>&nbsp;Otwarte</h5></div>       
              {{endelse}}
              {{endif}}
            </td>
          </tr>
        </tbody>
        {{endforeach}}
      </table>


    </section>
    {{endelse}}
    {{endif}}
  </div>
  <div class="saCharacterTab ipsColumn_fluid tab_6">
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      {{if $logs}}

      <table id="sarpTable" class='ipsPad'>
        <tr class="header">
          <th data-key="UID">         
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Data logowania</strong></h5></div>
          </th>         
          <th data-key="Model">         
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Adres IP</strong></h5></div>
          </th>         
          <th></th>
        </tr>
        {{foreach $logs as $row}}
        <tbody data-role="tableRows">
          <tr class="ipsClearfix" data-keynavblock="">  
            <td class="ipsTable_primary ipsType_light"> 
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{datetime="$row['log_date']"}</h5></div>
            </td>
            <td>
              <div class="ipsDataItem_title">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">{$row['log_ip']}</h5></div>
              </div>  
            </td>
          </tr>
        </tbody>
        {{endforeach}}
      </table>
      {{else}}
      <div class="ipsMessage ipsMessage_warning">
        Postać nie posiada zapisanych żadnych sesji logowań.
      </div>
      {{endif}}
    </section>
  </div>
</div>
{{endif}}