<ips:template parameters="$darknet" />
<table class="ipsTable ipsTable_responsive" data-role="table">
<div class='ipsMessage ipsMessage_info'>
  <span class='ipsMessage_code'>Witaj w <strong>DarkNecie</strong></span>
	Zakładka ta ma na celu informowania o obecnych aukcjach graczy.
  <br>Chcemy aby wszyscy mogli zobaczyć aukcje i jakie ceny na nich występują wtedy rządza zdobycia numeru do DarkNetu będzie jeszcze większa.<br>Wszystkie aukcje są widoczne poniżej, również z nazwą przedmiotu, ceną oraz UID.<br><br>Zakupienie przedmiotu odbywa się tylko i wyłącznie w grze, jeżeli chcesz aukcje przejąć i kupić przedmiot wystarczy zdobyć numer do DarkNetu od bota, którego sami musicie znaleźć w Fort Carson.<br>Gdy już to uczynicie, wystarczy zadzwonić pod podany numer telefonu aby otworzyć aukcje i dokonać zakupu.
</div>
      <thead>
        <tr class="ipsAreaBackground">		

          <th  data-key="UID">					
            UID
          </th>	

          <th  data-key="Przedmiot">					
            Przedmiot
          </th>	

          <th data-key="Cena">	
            Cena
          </th>   
       
        </tr>
      </thead>
      {{foreach $darknet as $row}}
      <tbody data-role="tableRows">
        <tr class="ipsClearfix" data-keynavblock="">	

          <td data-title="ID">	
            <div class="ipsDataItem_title ipsType_light">{$row['item_uid']}</div>
          </td> 

           <td data-title="Przedmiot">	
              <div class="ipsDataItem_title ipsType_light">{$row['item_name']}</div>
          </td> 

          <td data-title="Cena">	
            <div class="ipsDataItem_title">${$row['item_price']}</div>
          </td> 
		{{endforeach}}
        </tr>
      </tbody>
    </table>
