<ips:template parameters="$characters" />
<div class='ipsMessage ipsMessage_info' style="    background: linear-gradient(45deg, #1c5592, #223B64);">
  <span class='ipsMessage_code'>Witaj w panelu Twoich <strong>postaci.</strong></span><br><br>
	W tym miejscu możesz podglądać wszystkie informacje o Twojej postacie.<br>Dodatkowo została dodana nowa opcja ukrywania postaci dla użytkowników, którzy posiadają konto premium GOLD na serwerze.<br>Póki co nie mamy zamiaru wprowadzać konta premium do zakupu, może się to rzecz jasna zmienić jeśli to Wy będziecie tego chcieli.<br><br>Obecnie konto premium możecie zyskać na Eventach organizowanych przez EventTeam lub innych unikalnych wydarzeniach, które będą gościć na serwerze.
</div>
<br><br>
<div style="line-height: 15px">
  <h2 class="ipsType_sectionTitle ipsType_reset cForumTitle" style="float: left; ">Postacie przypisane do Twojego konta</h2>
  <a href="index.php?app=game&module=ajax&controller=createCharacter" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Tworzenie nowej postaci">
    <span class="ipsBadge ipsBadge_large ipsBadge_positive" style="margin-left: 15px;">
      <i class='fa fa-plus fa-lg'></i> Dodaj nową postać
    </span>
  </a>
  
</div>

<hr class="ipsHr">
{{foreach $characters as $row}}
{{if $row['char_active'] == 1}}
<a href="index.php?app=game&module=ajax&controller=showCharacter&id={$row['uid']}" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="{$row['name']} ({$row['uid']})">
    <div class="saCharacter" style="margin-right: 15px; margin-top: 15px;">
      {{if $row['char_typ'] == 1}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Biznesmen</span>{{endif}}
        {{if $row['char_typ'] == 2}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Gangster</span>{{endif}}
        {{if $row['char_typ'] == 3}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Cywil</span>{{endif}}
      {{if $row['skin'] >  300}}<img src="https://wynalazca.tv/wp-content/uploads/2017/09/pytajnik-wynalazek-patent-min.png" style="opacity: 0.3"><br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['skin']}.png" style="opacity: 0.3"><br/>{{endif}}
      <div style="margin-top: 5px;">
        <p class="saCharacterFont">{$row['name']}</p>
        <p class="saCharacterFont ipsType_negative">BLOKADA</p>
      </div>
    </div>
  </a>
{{elseif $row['czy_online'] == 1}}
<a href="index.php?app=game&module=ajax&controller=showCharacter&id={$row['uid']}" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="{$row['name']} ({$row['uid']})">
    <div class="saCharacter" style="margin-right: 15px; margin-top: 15px; border-color: #4f9c41">
      {{if $row['char_typ'] == 1}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Biznesmen</span>{{endif}}
        {{if $row['char_typ'] == 2}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Gangster</span>{{endif}}
        {{if $row['char_typ'] == 3}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Cywil</span>{{endif}}
      {{if $row['skin'] > 300}}<img src="https://wynalazca.tv/wp-content/uploads/2017/09/pytajnik-wynalazek-patent-min.png" style=""><br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['skin']}.png" class="imgGame" style=""><br/>{{endif}}
      <div style="margin-top: 5px;">
        <p class="saCharacterFont">{{if $row['ukryta'] == 1}}<i class="fa fa-eye ipsType_light" style="font-size: 125%;"></i> {{endif}}{$row['name']}</p>
        <p class="saCharacterFont">{$row['online_hours']}h {$row['online_minutes']}min</p>
      </div>
    </div>
  </a>
{{else}}
<a href="index.php?app=game&module=ajax&controller=showCharacter&id={$row['uid']}" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="{$row['name']} ({$row['uid']})">
    
  <div class="saCharacter " style="margin-right: 15px; margin-top: 15px">
     {{if $row['char_typ'] == 1}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Biznesmen</span>{{endif}}
        {{if $row['char_typ'] == 2}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Gangster</span>{{endif}}
        {{if $row['char_typ'] == 3}} <span class="ipsBadge ipsBadge_large ipsBadge_typ" style="margin-left: 15px; background:linear-gradient(45deg, #1c5592, #223B64);">Cywil</span>{{endif}}
      {{if $row['skin'] > 300}}<img src="https://wynalazca.tv/wp-content/uploads/2017/09/pytajnik-wynalazek-patent-min.png" style=""><br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['skin']}.png" style=""><br/>{{endif}}
      <div style="margin-top: 5px;">
        <p class="saCharacterFont">{{if $row['ukryta'] == 1}}<i class="fa fa-eye ipsType_light" style="font-size: 125%;"></i> {{endif}}{$row['name']}</p>
        <p class="saCharacterFont">{$row['online_hours']}h {$row['online_minutes']}min</p>
      </div>
    </div>
  </a>
{{endelseif}}
{{endif}}
{{endforeach}}

<div style="clear: both"></div>
<br>
                                        <!--  <h3 class="hrpTitle">Aktualnie na serwerze</h3><br><br>
<div style="clear: both"></div>
	{{if count(\IPS\game\Character::fetchCharactersOnline()) == 0}} 
<div class='ipsMessage ipsMessage_info'>
	Aktualnie na serwerze nie przebywa żaden gracz.
</div>
	{{else}}

<div class='ipsGrid ipsGrid_collapsePhone cStaffDirectory_blocks' style="margin-top: -50px;">
  {{foreach \IPS\game\Character::fetchCharactersOnline() as $row}}
  {{if  $row['grupa'] == 4}}
   <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['char_visible'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2 ipsAreaBackground' style="margin-top: 15px; margin-left: 10px; background:none;  max-width: 66px; min-height: 66px; padding: 2px">
 <a href="https://sa-rp.pl/index.php?/profile/{$row['char_gid']}-redirect/" class="ipsUserPhoto ipsUserPhoto_small admin" syle="border-radius:100px;">
   {{elseif  $row['grupa'] == 6}}
   <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['char_visible'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2 ipsAreaBackground' style="margin-top: 15px; margin-left: 10px; background:none;  max-width: 66px; min-height: 66px; padding: 2px">
 <a href="https://sa-rp.pl/index.php?/profile/{$row['char_gid']}-redirect/" class="ipsUserPhoto ipsUserPhoto_small gm" syle="border-radius:100px;">
    {{endelseif}} 
   {{elseif $row['premium'] > time()}}
     <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['char_visible'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}} - (Konto Premium GOLD)" class='ipsGrid_span2 ipsAreaBackground' style="margin-top: 15px; margin-left: 10px; background:none;  max-width: 66px; min-height: 66px; padding: 2px">
 <a href="https://sa-rp.pl/index.php?/profile/{$row['char_gid']}-redirect/" class="ipsUserPhoto ipsUserPhoto_small premium" syle="border-radius:100px;">
   {{endelseif}}
   {{else}}
    <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['char_visible'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2 ipsAreaBackground' style="margin-top: 15px; margin-left: 10px;  background:none; max-width: 66px; min-height: 66px; padding: 2px">
    <a href="https://sa-rp.pl/index.php?/profile/{$row['char_gid']}-redirect/" class="ipsUserPhoto ipsUserPhoto_small">
      {{endelse}}
      {{endif}}
      
        <img src="{$row['photo']}">
      </a>
    </div>
    {{endforeach}}
  </div>
  {{endelse}}
  {{endif}}<br>
-->
<!--
 <h3 class="hrpTitle">Top godziny na postaciach</h3>
  <ul style="    padding: 10px 20px 0px 15px;" class="">
<table style="width:100%;">
  <th>Nazwa Postaci</th>
  <th>Konto globalne</th>
    {{foreach \IPS\game\Character::CharHours() as $row}}
  <tr>
    <li style="opacity: 0.8;
    text-shadow: 0px 0px 0px #0d273e;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    box-shadow: inset 0px 0px 0px rgba(0,0,0,0.2);
    border-left: 2px solid #d7e8f5;
    padding-left: 1.5em;
    font-size: 15px;
             list-style:none;" class="">
     <th class="tg-cly1hrp">
  
<a hovercard-ref="member" href="https://h-rp.eu/index.php?/profile/{$row['char_gid']}-redirect/" ><span itemprop="name">{$row['char_name']}</span></a>
    </th>
    <th class="tg-cly1hrp">
     <font color="#b63f3f
  ">({$row['nickname']})</font>
    </th>
    <th class="tg-cly1hrp">
<span class="a" style="background-color: #eff8ff; margin: 0px; padding: 0px 4px; float:right;">
{$row['char_hours']}h 
</span>
    </th>
  <th>
  {$row['char_minutes']}min
  </th>
</li>
   
    </tr>
  {{endforeach}}
    </table>
</ul>
  <!-- <h3 class="hrpTitle">Najbogatsza postać</h3>
  <ul>

    {{foreach \IPS\game\Character::charBogaty() as $row}}

    <li style="opacity: 0.8;
    text-shadow: 0px 0px 0px #0d273e;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    box-shadow: inset 0px 0px 0px rgba(0,0,0,0.2);
   
    max-width:100px;
    font-size: 15px;
             list-style:none;" class="">
<center>
   {{if $row['char_skin'] > 300}}<img src="https://h-rp.eu/images/skins/unknow.png" style="opacity: 0.8"><br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['char_skin']}.png" style="opacity: 0.8"><br/>{{endif}}
       <br>
<a hovercard-ref="member" href="https://h-rp.eu/index.php?/profile/{$row['char_gid']}-redirect/" ><span itemprop="name">{$row['char_name']}</span></a>
      </center>

</li>
  {{endforeach}}
 
</ul> -->
<!--
    <h3 class="hrpTitle">3 najbogatsze grupy</h3>
  <ul style="padding:0;">
<table style="width:100%;">

    {{foreach \IPS\game\Character::GroupBogaty() as $row}}
  <tr>
    <li style="opacity: 0.8;
    text-shadow: 0px 0px 0px #0d273e;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    box-shadow: inset 0px 0px 0px rgba(0,0,0,0.2);
    font-size: 15px;
               padding-bottom:5px;
             list-style:none;" class="">

<th  class="hrpth">
<a hovercard-ref="member" ><span itemprop="name">{$row['group_name']}</span></a>
</th>
<th class="hrpth">
<a hovercard-ref="member" ><span itemprop="name">${$row['group_cash']}</span></a>
      </th>

</li>
    </tr>
  {{endforeach}}
  
    </table>
</ul>-->