<ips:template parameters="$report" />
<table class="ipsTable ipsTable_responsive" data-role="table">
<div class='ipsMessage ipsMessage_success'>
  <span class='ipsMessage_code'>Witaj w <strong>zgłoszeniach 911</strong></span>
Ta zakładka została stworzona specjalne aby uświadomić wszystkim jakim zaawansowanym systemem jest system zgłoszeń na serwerze.<br>Wszystkie zgłoszenia zostają zapisane do bazy danych i będą wiedzieć do końca serwera.<br>Dużo dostepnych opcji również ma sam Sheriff’s Communication Center, który tymi zgłoszeniami zarządza.<br>Pamiętajcie, że wszystkie zgłoszenia InCharacter są dość istotne w rozgrywce In Character tak jak w realnym świecie <i class="fas fa-phone"></i>.
</div>
      <thead>
        <tr class="ipsAreaBackground">		

          <th  data-key="UID">					
            UID
          </th>	

          <th  data-key="Przedmiot">					
            Treść zgłoszenia
          </th>	

          <th data-key="Cena">	
            Zgłaszający
          </th>   
       
        </tr>
      </thead>
    {{if !$report}}
    <div class="ipsBox ipsPad">
      <div class='ipsMessage ipsMessage_error'>
        Obecnie nie ma żadnych zgłoszeń 911.
      </div>
    </div>
    {{else}}
      {{foreach $report as $row}}

      <tbody data-role="tableRows">
        <tr class="ipsClearfix" data-keynavblock="">	

          <td data-title="ID">	
            <div class="ipsDataItem_title ipsType_light">{$row['report_uid']}</div>
          </td> 

           <td data-title="Przedmiot">	
              <div class="ipsDataItem_title ipsType_light">{$row['report_text']}</div>
          </td> 

          <td data-title="Cena">	
            <div class="ipsDataItem_title">{$row['report_player_create']}</div>
          </td> 
       
		{{endforeach}}
             {{endif}}
        </tr>
      </tbody>
    </table>
