<ips:template parameters="$sarpdev" />
<div class='ipsPad'>
  <div class='ipsColumns ipsColumns_bothSpacing ipsColumns_halfSpacing'>
	<div class='ipsColumn ipsColumn_fluid ipsBox ipsPad ipsType_center' style='height: 200px; margin-center: auto'>
    
    	<img src='{$sarpdev['image']}'>
    
    </div>
	<div class='ipsColumn ipsColumn_fluid ipsAreaBackground_light ipsPad'>
    
    	<div class="ipsWidget_inner ipsPad">
              <ul class="ipsDataList ipsDataList_reducedSpacing">
                <li class="ipsDataItem">
                  <span class="ipsDataItem_generic ipsDataItem_size3 ipsType_break"><strong>ID</strong></span>
                  <span class="ipsDataItem_main">{$sarpdev['info1']} </span>
                </li> 
                <li class="ipsDataItem">
                  <span class="ipsDataItem_generic ipsDataItem_size3 ipsType_break"><strong>Typ</strong></span>
                  <span class="ipsDataItem_main">{{if $sarpdev['type'] == 1}} Obiekt {{else}} Skin {{endelse}} {{endif}}</span>
                </li> 
                <li class="ipsDataItem">
                  <span class="ipsDataItem_generic ipsDataItem_size3 ipsType_break"><strong>Dodane</strong></span>
                  <span class="ipsDataItem_generic">{datetime="$sarpdev['date']"}</span>
                </li>
                <li class="ipsDataItem">
                  <span class="ipsDataItem_generic ipsDataItem_size3 ipsType_break"><strong>Dodane przez</strong></span>
                  <span class="ipsDataItem_generic">
                    <a href="http://sa-rp.pl/index.php?/profile/{$sarpdev['autor']}-redirect/" data-ipshover="" data-ipshover-target="http://sa-rp.pl/index.php?/profile/{$sarpdev['autor']}-redirect/&do=hovercard">
                      {$sarpdev['nick']}
                    </a>
                  </span>
                </li>              
              </ul>
            </div>
      
    </div>
  </div>
  {{if $sarpdev['type'] == 1}}
  <hr class='ipsHr'>
  	<div class='ipsAreaBackground_dark ipsPad'>
      <span class='ipsType_minorHeading ipsType_normal'><b>Stworzenie obiektu w grze</b></span>
     <pre class="ipsCode prettyprint lang-html prettyprinted">
<span class="com">/mc</span> <span class="atv"> {$sarpdev['info1']}</span></pre>
  </div> {{endif}}
</div>