<ips:template parameters="$ticketData, $posts, $form" />
<script>
  function editReply(id)
  {
    $("#reply_"+id).hide(); 
    $("#reply_hidden_"+id).show(); 
  }
</script>
<div id="ipsLayout_mainArea">
  <div class="ipsPageHeader ipsClearfix">
    <div class="ipsPhotoPanel ipsPhotoPanel_small ipsPhotoPanel_notPhone ipsClearfix" style="float: left;">
      {template="userPhoto" group="global" app="core" params="\IPS\Member::load( $ticketData['user_id'] ), 'small'"}
      <div>
        <h1 class="ipsType_pageTitle">
          <span class="ipsType_break" data-controller="core.front.core.moderation">
            {$ticketData['title']}
          </span>
        </h1>
        <p class="ipsType_reset ipsType_blendLinks ipsSpacer_bottom ipsSpacer_half">
          <span class="ipsType_normal">
            Przez {expression="\IPS\Member::load( $ticketData['user_id'] )->name"} {datetime="$ticketData['time']"}
          </span>
        </p>
      </div>
    </div>
    {{if \IPS\Request::i()->module == admincp}}
    <div style="float: right">
      <a href="#elTickets_options_menu" id="elTickets_options" class="ipsButton ipsButton_veryLight ipsButton_small" data-ipsmenu="" data-ipsmenu-selectable="">
        Zarzadzaj zgłoszeniem
        <i class="fa fa-caret-down"></i>
      </a>
      <ul id="elTickets_options_menu" class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide ipsMenu_bottomRight" animating="false">
        <li class="ipsMenu_item" data-ipsmenuvalue="wrap"><a href="index.php?/admincp/&tab=tickets&showTicket={$ticketData['id']}&action=close">Zamknij zgłoszenie</a></li>
        <li class="ipsMenu_item" data-ipsmenuvalue="lines"><a href="index.php?/admincp/&tab=tickets&showTicket={$ticketData['id']}&action=done">Oznacz jako ukończone</a></li>
        <li class="ipsMenu_item" data-ipsmenuvalue="diff"><a href="index.php?/admincp/&tab=tickets&showTicket={$ticketData['id']}&action=inprogress">Oznacz jako w trakcie</a></li>
      </ul>
    </div>
    {{endif}}
  </div>
  <div class="ipsBox" style="padding: 15px;">
    {$ticketData['content']|raw}
    {{if \IPS\Member::loggedIn()->member_id == $ticketData['user_id']}}
      {{if $ticketData['status'] != 3 }}
      <div class="ipsItemControls">
        <ul class="ipsComment_controls ipsClearfix ipsItemControls_left" data-role="commentControls">
          <li><a href="index.php?/character/&tab=tickets&editTicket={$ticketData['id']}">Edytuj</a></li>
        </ul>
      </div>
      {{endif}}
    {{endif}}
  </div>
  <br/>
{{if $posts}}
  <h2 class="ipsType_sectionTitle ipsType_reset">Odpowiedzi</h2>
  <div class="ipsAreaBackground_light ipsPad">
    {{foreach $posts as $row}}
    <div data-role="commentFeed">					
      <a name="comment-8"></a>
      <div class="ipsBox ipsSpacer_bottom  ipsComment ipsComment_parent">
        <div class="{{if $row['author'] == $ticketData['user_id']}} saSupportMessage_m {{else}} saSupportMessage_s {{endif}} ipsColumns ipsColumns_collapsePhone">
          <div class="ipsColumn ipsColumn_medium ipsType_center" {{if $row['author'] != $ticketData['user_id']}} style="background: #eef2f6" {{endif}}>
            <div class="ipsPad">
              {template="userPhoto" group="global" app="core" params="\IPS\Member::load( $row['author'] ), 'small'"}
              <br class="ipsSpacer_bottom">				
              <h3 class="ipsType_sectionHead ipsType_blendLinks"><strong>
                {expression="\IPS\Member::load( $row['author'] )->name"}
                </strong></h3>				
              <p class="ipsType_medium ipsType_reset">
                {expression="\IPS\Member::load( $row['author'] )->groupName" raw="true"}
              </p>
            </div>
          </div>
          <div class="ipsColumn ipsColumn_fluid cNexusSupportMessage_message">
            <div class="ipsPad">
              <div class="cNexusSupportMessage_date ipsType_medium">		
                <p class="ipsType_reset ipsType_light">
                  {datetime="$row['time']"}				
                </p>
              </div>
              <hr class="ipsHr">
              <div class="ipsType_richText ipsType_normal ">
                <div class="ipsType_normal ipsType_richText" id="reply_{$row['post_id']}">
                  {$row['content']|raw}
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>					
  </div>	
  {{endforeach}}
</div>
{{endif}}
<br />
  {{if $ticketData['status'] != 3 }}
	{$form|raw}
  {{else}}
  	<div class="ipsMessage ipsMessage_info">
      Te zgłoszenie zostało oznaczone jako <b>rozwiązane</b>.<br/>
      Jeżeli masz jakiekolwiek spostrzeżenia lub chciałbyś utworzyć nowe zgłoszenie - <a href="index.php?/character/&tab=tickets">wróć do listy zgłoszeń</a><br/>
      i utwórz <b>nowe zgłoszenie</b>.
    </div>
  {{endif}}
</div>