<ips:template parameters="$marketItems, $marketCars, $marketDoors" />

<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Market / budowa, zakładka widoczna tylko dla administratorów</h2>
<hr class="ipsHr"> 
{{if \IPS\Request::i()->action == 'makeOffert' }}
	Dodawanie oferty
{{else}}
<div class="ipsTabs saTabs ipsClearfix" id="ticketsTabs" data-ipstabbar="" data-ipstabbar-contentarea="#ticketsTabContent"> 
  <ul role="tablist" class="ipsList_reset" style="float: left">	
    <a class="ipsTabs_item saTabs_item ipsTabs_activeItem" id="cat_items" role="tab" aria-selected="true">
      <span class="saTabs_count" data-action="quickToggleCount"> <i class="fa fa-phone"></i></span>
      Przedmioty
    </a>
    <a class="ipsTabs_item saTabs_item" id="cat_cars" role="tab">
      <span class="saTabs_count" data-action="quickToggleCount"> <i class="fa fa-car"></i></span>
      Pojazdy
    </a>
    <a class="ipsTabs_item saTabs_item" id="cat_doors" role="tab">
      <span class="saTabs_count" data-action="quickToggleCount"><i class="fa fa-home"></i></span>
      Posiadłości
    </a>	
  </ul>
  <a href="index.php?/character/&tab=market&action=makeOffert" data-ipsdialog-title="Dodawanie oferty" style="float: right; padding-top: 10px; padding-right: 10px;">
    <span class="ipsBadge ipsBadge_large ipsBadge_intermediary">
      <i class="fa fa-plus"></i> Dodaj oferte
    </span>
  </a>
</div>
<section id="ticketsTabContent">
  <div id="ipsTabs_ticketsTabs_cat_items_panel" class="ipsTabs_panel" aria-labelledby="cat_items" aria-hidden="false" style="display: block;" animating="false">		
    <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">
      
        <div style="padding: 25px;">	
           {{foreach $marketItems as $row}}
          <li class="cForumRow ipsDataItem ipsDataItem_responsivePhoto  ipsClearfix">
            <div class="ipsDataItem_main" style="vertical-align: middle">
                <h4 class="ipsDataItem_title ipsType_large ipsType_break">
                  {{if $row['auction_priority'] == 1}}
                  <span class="ipsBadge ipsBadge_large ipsBadge_intermediary">Sponsorowane</span>  
                  {{endif}}
                  <a href="index.php?/character/&tab=market&viewMarketItem={$row['auction_id']}">{$row['auction_uid']}</a>
                </h4>
            </div>
           <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li class="ipsType_success">
                 <span class="ipsBadge ipsBadge_medium ipsBadge_positive">
                <strong><i class="fa fa-handshake-o"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_buynow']}</strong>
                </span>
              </li>
              {{if $row['auction_startprice'] == 0}}
               <li class="ipsType_light">
              	 -
              </li>
              {{else}}
              <li class="ipsType_light">
               <span class="ipsBadge ipsBadge_medium ipsBadge_neutral">
                <strong><i class="fa fa-gavel"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_startprice']}</strong>
                </span>
              </li>
              {{endelse}} {{endif}}
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li>
                <strong>{$row['auction_owner']}</strong>
              </li>
              <li>
                {datetime="$row['auction_date']"}
              </li>
            </ul>
          </li>
        {{endforeach}}
        </div>
      
    </ol>
  </div>
  <div id="ipsTabs_ticketsTabs_cat_cars_panel" class="ipsTabs_panel" aria-labelledby="cat_cars" aria-hidden="false" style="display: block;" animating="false">
    <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">
      
        <div style="padding: 25px;">
          {{if !marketCars}}
          	Brak wystawionych ofert
          {{else}}
          {{foreach $marketCars as $row}}
          <li class="cForumRow ipsDataItem ipsDataItem_responsivePhoto  ipsClearfix">
            <div class="ipsDataItem_main" style="vertical-align: middle">
                <h4 class="ipsDataItem_title ipsType_large ipsType_break">
                  {{if $row['auction_priority'] == 1}}
                  <span class="ipsBadge ipsBadge_large ipsBadge_intermediary">Sponsorowane</span>  
                  {{endif}}
                  <a href="index.php?/character/&tab=market&viewMarket={$row['auction_id']}">{$row['name']}</a>
                </h4>
            </div>
           <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li class="ipsType_success">
                 <span class="ipsBadge ipsBadge_medium ipsBadge_positive">
                   <strong><i class="fa fa-handshake-o"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_buynow']}</strong>
                </span>
              </li>
              {{if $row['auction_startprice'] == 0}}
               <li class="ipsType_light">
              	 -
              </li>
              {{else}}
              <li class="ipsType_light">
               <span class="ipsBadge ipsBadge_medium ipsBadge_neutral">
                <strong><i class="fa fa-gavel"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_startprice']}</strong>
                </span>
              </li>
              {{endelse}} {{endif}}
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li>
                <strong>{$row['auction_owner']}</strong>
              </li>
              <li>
                {datetime="$row['auction_date']"}
              </li>
            </ul>
          </li>
        {{endforeach}}
          {{endelse}} {{endif}}
        </div>
      
    </ol>
  </div>
  <div id="ipsTabs_ticketsTabs_cat_doors_panel" class="ipsTabs_panel" aria-labelledby="cat_doors" aria-hidden="false" style="display: block;" animating="false">
    <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">
      
         <div style="padding: 25px;">
          {{if !marketDoors}}
          	Brak wystawionych ofert
          {{else}}
          {{foreach $marketDoors as $row}}
          <li class="cForumRow ipsDataItem ipsDataItem_responsivePhoto  ipsClearfix">
            <div class="ipsDataItem_main" style="vertical-align: middle">
                <h4 class="ipsDataItem_title ipsType_large ipsType_break">
                  {{if $row['auction_priority'] == 1}}
                  <span class="ipsBadge ipsBadge_large ipsBadge_intermediary">Sponsorowane</span>  
                  {{endif}}
                  <a href="index.php?/character/&tab=market&viewMarket={$row['auction_id']}">{$row['nazwa']}</a>
                </h4>
            </div>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li class="ipsType_success">
                 <span class="ipsBadge ipsBadge_medium ipsBadge_positive">
                <strong><i class="fa fa-handshake-o"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_buynow']}</strong>
                </span>
              </li>
              {{if $row['auction_startprice'] == 0}}
               <li class="ipsType_light">
              	 -
              </li>
              {{else}}
              <li class="ipsType_light">
               <span class="ipsBadge ipsBadge_medium ipsBadge_neutral">
                <strong><i class="fa fa-gavel"></i> &nbsp; <i class="fa fa-usd" style="font-size: 95%"></i>{$row['auction_startprice']}</strong>
                </span>
              </li>
              {{endelse}} {{endif}}
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto" style="text-align: center">
              <li>
                <strong>{$row['auction_owner']}</strong>
              </li>
              <li>
                {datetime="$row['auction_date']"}
              </li>
            </ul>
          </li>
        {{endforeach}}
          {{endelse}} {{endif}}
        </div>
      
    </ol>
  </div>
</section>
{{endelse}}
{{endif}}