<ips:template parameters="$charsonline" />
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Gracze online 
</h2>
<hr class="ipsHr">
<div style="clear: both"></div>
	{{if count($charsonline) == 0}}
<div class='ipsMessage ipsMessage_info'>
	Aktualnie na serwerze nie przebywa żaden gracz.
</div>
	{{else}}

<div class='ipsGrid ipsGrid_collapsePhone cStaffDirectory_blocks' style="margin-top: -50px;">
  {{foreach $charsonline as $row}}
  {{if  $row['grupa'] == 4}}
    <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['ukryta'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2' style="margin-top: 15px; background-color: #F20008; margin-left: 10px;  max-width: 66px; min-height: 66px; padding: 2px">
   {{elseif  $row['grupa'] == 7}}
    <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['ukryta'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2' style="margin-top: 15px; background-color: #0F7715; margin-left: 10px;  max-width: 66px; min-height: 66px; padding: 2px">
    {{endelseif}}
      {{elseif $row['premium'] > time()}}
  <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako  {{if $row['ukryta'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2' style="margin-top: 15px; margin-left: 10px; background-color: #F2D488; max-width: 66px; min-height: 66px; padding: 2px">
    {{endelseif}}
    {{else}}
    <div data-ipstooltip="" _title="{$row['nickname']} zalogowany w grze jako {{if $row['ukryta'] == 1}} Postać ukryta {{else}} {$row['imie_nazwisko']} {{endelse}}{{endif}}" class='ipsGrid_span2 ipsAreaBackground' style="margin-top: 15px; margin-left: 10px;  max-width: 66px; min-height: 66px; padding: 2px">
      {{endelse}}
      {{endif}}
      <a href="http://h-rp.eu/index.php?/profile/{$row['gid']}-redirect/" class="ipsUserPhoto ipsUserPhoto_small">
        <img src="{$row['photo']}">
      </a>
    </div>
    {{endforeach}}
  </div>
  {{endelse}}
  {{endif}}