<ips:template parameters="$result" />
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Konto premium</h2>
<hr class="ipsHr">
<div>
  {{if $result}}
  <div class='ipsMessage ipsMessage_info'>
      $result
  </div>
  {{endif}}
  <div class='ipsColumns ipsColumns_bothSpacing ipsColumns_halfSpacing'>
     <div class='ipsColumn ipsBox ipsPad ipsColumn_veryWide ipsType_center'>
       <i class="fa fa-star ipsType_issue" style="font-size: 1000%"></i>
       <br />
       <span>
         <h1 class="ipsType_minorHeading ipsType_reset cForumTitle" style='font-size: 120%'>
       <p>Wszystkie środki z zakupionych kont premium zostają przekazane na rozwój serwera oraz niezbędne opłaty.</p>
          <p> Kupując usługę wspierasz <span class="ipsType_issue">dobrowolnie</span> projekt Harvest Role Play. </p></h1>
       </span>
       <div style='margin-top: 5px'>
       <span class="ipsBox ipsPad ipsType_light ipsType_minorHeading ipsType_reset cForumTitle" style='margin-top: 30px;'>
    {{if \IPS\game\Character::isPremium( \IPS\Member::loggedIn()->member_id) }}
         Posiadasz aktywne konto premium do <br><br><b class="ipsType_issue">{datetime="\IPS\Member::loggedIn()->member_premium_time"}</b>
    {{else}}
         Nie posiadasz aktywnego konta premium
    {{endif}}
       </span>
       </div>
             </div>
    <div class='ipsColumn ipsBox ipsPad ipsColumn_fluid'>
<table id="sarpTable" class='ipsPad'>
  <tr class="header">
     <th class="ipsType_minorHeading ipsType_reset cForumTitle" data-key="Grupa">					
              Opis usługi
            </th>					
            <th class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_neutral" data-key="Ubranie">					
              Standard
            </th>				
            <th class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_issue" data-key="Premium">	
              Premium
            </th>
  </tr>
 <tbody data-role="tableRows">
          <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
              GameScore za przegraną godzinę
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard">
              10
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>20</b>
            </td>
          </tr>
          <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
              Maksymalnie zespawnowane pojazdy
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard">
              1
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>3</b>
            </td>
          </tr>
           <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
              Maksymalnie zapisane opisy postaci
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard">
              3
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>6</b>
            </td>
          </tr>
          <tr>	
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
             Możliwość ukrywania postaci
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard">
              Nie
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>Tak</b>
            </td>
          </tr>
          <tr>
            <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
              Możliwość usuwania postaci
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard">
              nie
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>tak</b>
            </td>
          </tr>
   <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
             Dostęp do działu premium na forum
            </td>
            <td class="ipsType_light" data-title="Standard">
            Nie
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium">
              <b>Tak</b>
            </td>
          </tr>
        <tr>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle">	
              Wygląd nickname
            </td>
            <td class="ipsType_minorHeading ipsType_reset cForumTitle ipsType_light" data-title="Standard" style="color: #3d6594">
              {expression="\IPS\Member::loggedIn()->name"}
            </td>			
            <td class="ipsType_minorHeading ipsType_reset cForumTitle" data-title="Premium" style="color: #3d6594">
              <b>{expression="\IPS\Member::loggedIn()->name"}</b>
            </td>
          </tr>
         <tr>
        </tbody>
</table>
   
    </div><br />
  </div>

  <hr class="ipsHr">
  <div class='ipsColumns ipsColumns_bothSpacing ipsColumns_halfSpacing ipsType_center'>
    	<a href="index.php?app=game&module=ajax&controller=premium" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Proces aktywacji usługi premium - SMS">
          <span class="ipsButton ipsButton_veryLarge ipsButton_link ipsType_minorHeading ipsType_reset cForumTitle" style="margin-left: 15px">
            Kup konto premium <span class="ipsBadge ipsBadge_positive  ipsBadge_medium">SMS</span>
          </span>
  		</a>
  </div>
 