<ips:template parameters="$market, $auction, $characters" />
<div class='ipsColumns'>
	<div class='ipsColumn ipsColumn_fluid'>
      <div class='ipsFollowerList ipsScrollbar' style="max-height: 250px">
       <div class="ipsType_richText ipsBox"  style="min-height: 250px">
         <div class="ipsMenu_title ipsType_center ipsType_sectionTitle ipsType_reset cForumTitle" style="weight: 200px;"> Sprzedający <strong>
           {{if $market['auction_priority'] == 1}}  <i class="fa fa-star ipsType_issue"></i> {{endif}}
           {$market['imie_nazwisko']}</strong> &nbsp; <span class="ipsType_small ipsType_light ipsType_right">dodano {datetime="$market['auction_date']"}</span> </div>
			<div class="ipsPad">
      		  {$market['auction_desc']|raw}
         </div>
        </div>
      </div>
	</div>
  	<div class='ipsColumn ipsColumn_wide'>
      <div class="ipsType_richText ipsBox" style="min-height: 250px; max-height: 250px">
      	<div class="ipsMenu_title ipsType_center ipsType_sectionTitle ipsType_reset cForumTitle" style="weight: 200px;"> <strong> {$market['name']} </strong> </div>      
        <div class="ipsPad">
        
          <ul class="ipsDataList ipsDataItem ipsType_sectionTitle ipsType_reset cForumTitle" style="margin-top: -15px">
		         <li class="ipsDataItem" >
                   <div class="ipsDataItem_main ipsType_center" style="min-width: 130px;">
                     <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/196735-200.png" height="65px" weight="65px" style="margin: center">
         		 </div>
            	</li>
        <li class="ipsDataItem" >
          <div class="ipsDataItem_icon" style="min-width: 130px;">
             Wartość 1         
          </div>
          <div class="ipsDataItem_main ">
           
             <strong>{$market['value1']}</strong>          
            
          </div>
        </li>	
           
        <li class="ipsDataItem">
          <div class="ipsDataItem_icon" style="min-width: 130px;">
            Wartość 2    
          </div>
          <div class="ipsDataItem_main ">          
             <strong>{$market['value2']}</strong>          
          </div>
        </li>
            
      </ul>
        </div>
      </div>
  	</div>
  
	
</div>

 <hr class="ipsHr">
{{if $market['auction_status'] == 1}}
	{{if $market['auction_expire'] > time()}}
      <div class='ipsMessage ipsMessage_info'>
        Aukcja zostanie zakończona w dniu:
			<span class='ipsMessage_code'>{datetime="$market['auction_expire']"}</span>
		</div>
      {{else}}
       <div class='ipsMessage ipsMessage_success'>
        Aukcja została zakończona.
		</div>
      {{endelse}}
      {{endif}}
		{{else}}
		<div class='ipsMessage ipsMessage_success'>
       	 Aukcja została zakończona.
		</div>
{{endelse}} {{endif}}
<div class='ipsColumns'>
  
    <div class='ipsColumn ipsColumn_wide'>
      
      <div class="ipsType_richText ipsBox" style="min-height: 250px; max-height: 250px">
      		<div class="ipsMenu_title ipsType_center ipsType_sectionTitle ipsType_reset cForumTitle" style="weight: 200px;"> Szczegóły aukcji  </div>
        <div class="ipsPad">
         <ul class="ipsDataList ipsDataItem ipsType_sectionTitle ipsType_reset cForumTitle" style="margin-top: -15px">
           
		
        <li class="ipsDataItem" {{if $market['auction_buynow2'] == -1}} style='opacity: 0.2' {{endif}}>
          <div class="ipsDataItem_icon" style="min-width: 130px;">
            <i class="fa fa-handshake-o"></i> &nbsp; Kup teraz         
          </div>
          <div class="ipsDataItem_main ">
            <div class="ipsType_success">
              {{if $market['auction_buynow2'] == -1}} OFF {{else}}
             <i class="fa fa-usd" style="font-size: 85%"></i><strong>
              {$market['auction_buynow2']} {{endelse}} {{endif}}</strong>          
            </div>
          </div>
        </li>
         
           
        <li class="ipsDataItem" {{if $market['auction_startprice'] == -1}} style='opacity: 0.2' {{endif}}>
          <div class="ipsDataItem_icon" style="min-width: 130px;">
            <i class="fa fa-gavel"></i> &nbsp; Start licytacji     
          </div>
          <div class="ipsDataItem_main ">      
            {{if $market['auction_startprice'] == -1}} OFF {{else}}
             <i class="fa fa-usd" style="font-size: 85%"></i><strong>{$market['auction_startprice2']}</strong>      
            {{endelse}} {{endif}}
          </div>
        </li>
           
        <li class="ipsDataItem" {{if $market['auction_minpriceup'] == -1}} style='opacity: 0.2' {{endif}}>
          <div class="ipsDataItem_icon" style="min-width: 130px;">
             <i class="fa fa-gavel "></i> <i class="fa fa-arrow-up ipsType_success {{if $market['auction_minpriceup'] > -1}} sarpPulse {{endif}}"></i> &nbsp; min przebicie     
          </div>
          <div class="ipsDataItem_main ">
            {{if $market['auction_minpriceup'] == -1}} OFF {{else}}
            <div class="ipsType_success">
             <i class="fa fa-usd" style="font-size: 85%"></i><strong>{$market['auction_minpriceup2']}</strong>          
            </div>
            {{endelse}} {{endif}}
          </div>
        </li>	
           
      </ul>
        </div>
      </div>
  	</div>
  
	<div class='ipsColumn ipsColumn_fluid'>
      <div class='ipsFollowerList ipsScrollbar' style="max-height: 250px">
       <div class="ipsType_richText ipsBox"  style="min-height: 250px">
         <div class="ipsMenu_title ipsType_center ipsType_sectionTitle ipsType_reset cForumTitle" style="weight: 200px;"> Historia licytacji  </div>
			<div class="ipsPad">
             <table class="ipsTable ipsTable_responsive ipsTable_zebra " data-role="table" data-ipskeynav="" data-ipskeynav-observe="e d return">
                  {{foreach $auction as $auction}}     		  
                <tbody data-role="tableRows">
                  
          <tr class="ipsClearfix ipsAreaBackground_light" data-keynavblock="">	
            
            <td class="ipsTable_wrap" data-title="Pracownik">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <a href="http://sa-rp.pl/index.php?/profile/{$auction['character_gid']}-redirect/" data-ipshover="" data-ipshover-target="http://sa-rp.pl/index.php?/profile/{$auction['character_gid']}-redirect/&do=hovercard" class="ipsUserPhoto ipsUserPhoto_tiny">
                  <img src="{$auction['photo']}">
                </a>
              <div class="ipsDataItem_title">
                 {{if $market['auction_latest_user'] == $auction['character_gid'] AND $market['auction_latest_price'] == $auction['cash'] }}  <i class="fa fa-trophy ipsType_issue"></i> {{endif}}
                {{if $auction['type'] == 1}} <i class="fa fa-handshake-o ipsType_issue"></i> {{endif}}
                   <a href="http://sa-rp.pl/index.php?/profile/{$auction['character_gid']}-redirect/">{$auction['imie_nazwisko']}</a></div>
              </div>            
            </td>   
            
          
           <td data-title="Przebitka">
              
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">
                  <div class="ipsDataItem_title ipsType_positive 
                              {{if $market['auction_latest_price'] == $auction['cash'] }} sarpPulse {{endif}}">
                    <i data-ipstooltip="" class="fa fa-dollar"></i>
                    {$auction['cash2']}</div>
                </h5></div>
             
            </td>
            
            <td class="ipsTable_wrap" data-title="Konto">
					
						
              <div class="ipsType_break">

              <span class="ipsType_sectionTitle ipsType_small cForumTitle ipsType_light">{datetime="$auction['date']"}</span><br>
              </div>

				</td>
            
                 </tr>
              </tbody>
                {{endforeach}}
              </table>
         </div>
        </div>
      </div>
	</div>
  
</div>

 <hr class="ipsHr">
	{{if $market['auction_owner_gid'] == \IPS\Member::loggedIn()->member_id AND $market['auction_status'] == 2 AND $market['auction_owner_takecash'] == 0}}
		<div class="ipsAreaBackground ipsPad ipsType_center ipsType_success ipsType_sectionTitle" style="padding: 15px">
     		Aukcja została zakończona. <span class='ipsBadge ipsBadge_large ipsBadge_positive'>ODBIERZ ( ${$market['auction_buynow2']} )</span> za sprzedany przedmiot!
    	</div>
	{{elseif $market['auction_owner_gid'] == \IPS\Member::loggedIn()->member_id AND $market['auction_status'] == 2 AND $market['auction_owner_takecash'] == 1}}
		<div class="ipsAreaBackground ipsPad ipsType_center ipsType_warning ipsType_sectionTitle" style="padding: 15px">
  		  Aukcja została zakończona, a Ty już odebrałeś swoją gotówkę za sprzedany przedmiot.
      </div>
  {{elseif $market['auction_owner_gid'] == \IPS\Member::loggedIn()->member_id}}
    <div class="ipsAreaBackground ipsPad ipsType_center ipsType_warning ipsType_sectionTitle" style="padding: 15px">
     Nie możesz operować transakcjami w przypadku, kiedy aukcja należy do Ciebie
    </div>
	{{elseif $market['auction_status'] == 2}}
    <div class="ipsAreaBackground ipsPad ipsType_center ipsType_warning ipsType_sectionTitle" style="padding: 15px">
     Ta aukcja została już zakończona
    </div>
  {{else}}

<div class='ipsColumns' {{if $market['auction_expire'] < time() }} style='opacity: 0.3' {{endif}} >
	<div class='ipsColumn ipsColumn_wide ipsType_center ipsAreaBackground'>
      {{if $market['auction_buynow2'] == -1}} 
      <div
        class="ipsPad ipsButton ipsButton_medium ipsButton_disabled " style="margin-top: 40px; {{if $market['auction_buynow2'] == -1}} opacity: 0.2; {{endif}}">
        Opcja Kup teraz wyłączona
      </div>
      {{else}}
     <a href='#buynow' data-ipsDialog data-ipsDialog-title="{$market['name']} - ${$market['auction_buynow2']}" data-ipsDialog-content="#buynow" data-ipsdialog-size="narrow"
        class="ipsPad ipsButton ipsButton_medium  {{if $market['auction_expire'] < time()}} ipsButton_disabled {{endif}} ipsButton_important" style="margin-top: 40px; {{if $market['auction_buynow2'] == -1}} opacity: 0.2; {{endif}}">
        Kup teraz ( ${$market['auction_buynow2']} )
        </a>
    	{{endelse}}
      {{endif}}
       <div id='buynow' class='ipsHide'>
         
         <div class='ipsPad'>
           <span style="font-size: 120%">
       		 1.&nbsp; Kupując przedmiot, nie ma żadnych możliwości, aby ubiegać się o jakiekolwiek zwroty.<br />
           2.&nbsp; Nie będą tolerowane <b class="ipsType_warning">żadne</b> tłumaczenia, klikajac poniższy przycisk <b class="ipsType_success">potwierdzasz</b>, że jesteś pewien zakupu.</span>
         </div>
        
         <div class='ipsPad ipsType_center ipsAreaBackground'>
           <form action="" method="POST">
            <p style="padding-left: 15px">
              <span class="ipsType_small">Postać z której kupuję</span>
              
              <select name="buy_char_id">
                {{foreach $characters as $row}}
                <option value="{$row['id']}">{$row['imie_nazwisko']} &nbsp;&nbsp;&nbsp;&nbsp; |  &nbsp;&nbsp;&nbsp;&nbsp; Bank:  ${$row['bank']}</option>
                {{endforeach}}
              </select>
              
              <br /> <hr class='ipsHr'>
              
                <b>Akceptuję powyższy regulamin,</b> &nbsp;
               <input class="ipsButton ipsButton_important ipsButton_small {{if $market['auction_expire'] < time()}} ipsButton_disabled {{endif}}" type="submit" value="Kupuję {$market['name']}">
           </form>

         </div>
      </div>
      
	</div>     

  	<div class='ipsColumn ipsColumn_fluid'>
      <div class="ipsPad ipsBox" {{if $market['auction_startprice'] == -1}} style='opacity:0.2' {{endif}}>
<div style="text-align: center">
  <form action="" method="GET">
	<p style="padding-left: 15px">
      <span class="ipsType_small ipsType_light">Postać z której licytuje</span>
      <select name="cos">
        {{foreach $characters as $row}}
        <option {{if $market['auction_startprice'] == -1}} disabled='' {{endif}} value="{$row['id']}">{$row['imie_nazwisko']} &nbsp;&nbsp;&nbsp;&nbsp; |  &nbsp;&nbsp;&nbsp;&nbsp; Bank:  ${$row['bank']}</option>
        <span class="ipsBadge ipsBadge_warning ipsBadge_large"> {$row['bank']} </span>
        {{endforeach}}
      </select>
      
    </p>
      <span class="ipsType_small ipsType_light">Kwota którą licytuje</span>
    <i data-ipstooltip="" class="fa fa-dollar"></i> <input {{if $market['auction_startprice'] == -1}} disabled='' {{endif}} class="ipsField_short" name="Wprowadź kwotę" type="number" min="{$market['auction_latest_price'] + 1}" placeholder="{$market['auction_latest_price'] + 1}" value="">
    
      <input {{if $market['auction_startprice'] == -1}} disabled='' {{endif}} class="ipsButton ipsButton_primary ipsButton_verySmall {{if $market['auction_expire'] < time()}} ipsButton_disabled {{endif}}" type="submit" value="Wystaw ofertę">
    
  </form>
</div>
      </div>
  	</div>	
</div>
  {{endelse}}
{{endif}}