<ips:template parameters="$groupData, $perm, $income " />
<script type="text/javascript" src="uploads/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Dzień', 'Zarobek'],
      {{if $income}}
        {{foreach $income as $row}}
        ['{datetime="$row['date']" dateonly="true"}',  {expression="$row['roznica']"}],
        {{endforeach}}
      {{else}}
        [0, 0],                                       
      {{endif}}
    ]);

    var options = {
      title: '',
      hAxis: {title: 'Data',  titleTextStyle: {color: '#333'}},
      vAxis: {minValue: 0}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>
<div style="background-color: #e6e8eb">
  <div class="saGroupTab ipsColumn_fluid tab_1" style="display: block; top: -20px">     
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      <div class="ipsColumns">
        <div class="ipsColumn ipsColumn_fluid">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h4 class="ipsDataItem_title"><strong>Wykres zarobków</strong></h4><br>
          </div>
          <ul class="ipsDataList ipsBox ipsPad">
            <div class="ipsColumn ipsColumn_wide">
              <div id="chart_div" style="width: 100%; height: 300px;"></div>
            </div>
          </ul>
        </div>
        <div style="clear: both"></div>
      </div>
    </section><br />
    <section id="elProfileTabContent" class="ipsBox ipsPad">	
      <div class="ipsColumns">
        <div class="ipsColumn ipsColumn_wide">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h4 class="ipsDataItem_title"><strong>Informacje</strong></h4><br>
          </div>
          <ul class="ipsDataList ipsBox ipsPad">
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Typ grupy</strong></h4><br>  
                {$groupData['typgrupy']}        	   
              </div></li>
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>TAG</strong></h4><br>
                {$groupData['tag']}     
              </div>
            </li>	
            <li class="ipsDataItem">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h4 class="ipsDataItem_title"><strong>Właściciel</strong></h4><br>
                {$groupData['imie_nazwisko']}     
              </div>
            </li>	
          </ul>
        </div>
        <div class="ipsColumn ipsColumn_wide">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h4 class="ipsDataItem_title"><strong>Statystyki</strong></h4><br>
          </div>
          <div id="elProfileInfoColumn">
            <ul class="ipsDataList ipsBox ipsPad">
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Punkty aktywności</strong></h4><br>
                  {{if $groupData['points'] > 999 }}
                  <i data-ipstooltip="" _title="Grupa kwalifikuje się do wypłat, ponieważ przekroczyła wymagany prób punktów aktywności!" class="fa fa-circle ipsType_positive"></i>
                  {$groupData['points']} / 1000
                  {{else}}
                  <i data-ipstooltip="" _title="Grupa nie kwalifikuje się do rozdania wypłat. Minimalny próg punktów aktywności wynosi 1000!" class="fa fa-circle ipsType_negative"></i>
                  {$groupData['points']} / 1000
                  {{endelse}} {{endif}}
                </div>
              </li>
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Stan konta</strong></h4><br>
                  <div class="ipsType_positive"><strong>$</strong> {$groupData['f-cash']} </div>   
                </div>
              </li>
              <li class="ipsDataItem">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h4 class="ipsDataItem_title"><strong>Dotacja</strong></h4><br>
                  $ {$groupData['dotacja']}
                </div>
              </li>			
            </ul>
          </div>
        </div>
        {{if $perm & 1}}
        <div class="ipsColumn ipsColumn_fluid">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h4 class="ipsDataItem_title"><strong>Ustawienia</strong></h4><br>
          </div>
          <ul class="ipsDataList ipsBox ipsPad">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">  
               <h4 class="ipsDataItem_title">TAG</h4><br>
               <form action="" method="POST">
                <input name="tag" aria-required="false" value="{$groupData['tag']}" type="text">
          		<br /><br />
              <h4 class="ipsDataItem_title">Kolor czatu</h4><br>
                <div  data-ipstooltip="" _title="{$groupData['chat']}" style="border: 1px #ddd solid; float: left; padding: 2px; border-radius: 2px; margin: 2px; width: 30px; height: 30px; background-color: rgb({$groupData['chat']});">                 
                </div>&nbsp;
                R: <input name="color_R" aria-required="false" class="ipsField_tiny" min="0" step="any" size="1" max="255" value="{$groupData['chat_color'][0]}" type="number">
                G: <input name="color_G" aria-required="true" class="ipsField_tiny" min="0" step="any" size="1" max="255" value="{$groupData['chat_color'][1]}" type="number">
                B: <input name="color_B" aria-required="true" class="ipsField_tiny" min="0" step="any" size="1" max="255" value="{$groupData['chat_color'][2]}" type="number">
                <br />
                 <div class="ipsType_center">
                <input type="submit" class="ipsButton ipsButton_primary ipsButton_verySmall" style="margin-top: 10px;" value="Zapisz ustawienia">
                 </div>
              </form>
            </div>      
          </ul>
        </div>
        {{endif}}
      </div>
    </section>
    <br />
    <section id="elProfileTabContent" class="ipsBox ipsPad">
      <div class="ipsColumns">
        <div class="ipsColumn ipsColumn_fluid">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h4 class="ipsDataItem_title"><strong>Flagi</strong></h4><br>
          </div>
          <ul class="ipsDataList ipsBox ipsPad">
            <div class="ipsColumn ipsColumn_wide">

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                {{if $groupData['flags'] & 1}}
                <i data-ipstooltip="" _title="Czat departamentowy" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Czat departamentowy" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Czat departamentowy
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 2}}
                <i data-ipstooltip="" _title=" Megafon" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title=" Megafon" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Megafon
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 4}}
                <i data-ipstooltip="" _title="Kolorowy nick-name" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Kolorowy nick-name" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Kolorowy nick-name
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 8}}
                <i data-ipstooltip="" _title="Opuszczanie grupy" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Opuszczanie grupy" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Opuszczanie grupy
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 16}}
                <i data-ipstooltip="" _title="Wypłacanie gotówki" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Wypłacanie gotówki" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Wypłacanie gotówki
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 32}}
                <i data-ipstooltip="" _title="Drive-by" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Drive-by" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Drive-by
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 64}}
                <i data-ipstooltip="" _title="Stawianie blokad" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Stawianie blokad" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Stawianie blokad
              </div>

            </div>
            <div class="ipsColumn ipsColumn_wide">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 128}}
                <i data-ipstooltip="" _title="Przetrzymywanie" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Przetrzymywanie" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Przetrzymywanie
              </div>
              
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 256}}
                <i data-ipstooltip="" _title="Zabieranie przedmiotów" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Zabieranie przedmiotów" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Zabieranie przedmiotów
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 512}}
                <i data-ipstooltip="" _title="Telefon alarmowy" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Telefon alarmowy" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Telefon alarmowy
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 1024}}
                <i data-ipstooltip="" _title="Zgłoszenia grupowe" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Zgłoszenia grupowe" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Zgłoszenia grupowe
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 2048}}
                <i data-ipstooltip="" _title="GPS w pojazdach" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="GPS w pojazdach" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                GPS w pojazdach
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 4096}}
                <i data-ipstooltip="" _title="Kogut" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Kogut" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Kogut
              </div>

              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">     
                {{if $groupData['flags'] & 8192}}
                <i data-ipstooltip="" _title="Wyważanie drzwi" class="fa fa-check-circle ipsType_positive"></i>
                {{else}}
                <i data-ipstooltip="" _title="Wyważanie drzwi" class="fa fa-times-circle ipsType_negative"></i>
                {{endelse}} {{endif}}
                Wyważanie drzwi
              </div>
            </div>
          </ul>
        </div>
        <div>         
        </div>
        <div style="clear: both"></div>
      </div>
    </section>
  </div>
</div>