<ips:template parameters="$groupDoors" />
  {{if !$groupDoors}}
    <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <div class="ipsPad">
    <div class='ipsMessage ipsMessage_warning'>
      Grupa nie posiada żadnych nieruchomości.
    </div>
  </div>
  {{else}}
 <div style="background-color: #e6e8eb; margin-top: -15px;">
  <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-building" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <section id="elProfileTabContent" class="ipsBox">
    <table id="sarpTable" class='ipsPad'>
        <tr class="header">		
          <th></th>
          <th  data-key="UID">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>ID</strong></h5></div>
          </th>	
          <th  data-key="Nazwa">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Drzwi</strong></h5></div>
          </th>					
          <th  data-key="Przejazd">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Możliwość przejazdu</strong></h5></div>
          </th> 
          <th data-key="Status">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Status drzwi</strong></h5></div>
          </th>
        </tr>
      {{foreach $groupDoors as $row}}
        <tr class="ipsClearfix" data-keynavblock="">	
          <td></td>
          <td data-title="ID">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['door_uid']}</h5></div>
          </td>
          <td data-title="Drzwi">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['door_name']}</h5></div>
          </td> 			
          <td data-title="Przejazd">
            <div class="ipsDataItem_title">{{if $row['door_garage'] == 1}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">
                  <i data-ipstooltip="" _title="Drzwi przejezdne" class="fa fa-check-circle ipsType_positive"></i> Przejazd otwarty
                </h5></div>
              {{else}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">
                  <i data-ipstooltip="" _title="Drzwi nie przejezdne" class="fa fa-times-circle ipsType_negative"></i> Przejazd zamknięty
                </h5></div>
              {{endelse}}{{endif}}
            </div>
          </td> 
          <td data-title="Status">
            {{if $row['door_lock'] == 1}}
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">
                <div class="ipsDataItem_title"><i data-ipstooltip="" _title="Drzwi zamkniete" class="fa fa-lock ipsType_negative"></i>&nbsp;Zamknięte</div> 
              </h5></div>
            {{else}}
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">
                <div class="ipsDataItem_title"><i data-ipstooltip="" _title="Drzwi otwarte" class="fa fa-unlock-alt ipsType_positive"></i>&nbsp;Otwarte</div> 
              </h5></div>      
            {{endelse}}
            {{endif}}
          </td>
        </tr>
      {{endforeach}}
    </table>
  </section>
</div>
  {{endelse}}
  {{endif}}