<ips:template parameters="$groupWorkers, $perm, $groupRanks" />
<div style="background-color: #e6e8eb">
  {{if !$groupWorkers}}
  <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-users" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-users" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-users" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <div class="ipsPad">
    <div class='ipsMessage ipsMessage_warning'>
      Grupa nie posiada żadnych zatrudnionych pracowników.
    </div>
  </div>
  {{else}}
  <div style="background-color: #e6e8eb; margin-top: -15px;">
    <div style="text-align: center; margin-bottom: 15px;">
      <i class="fa fa-users" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
      <i class="fa fa-users" aria-hidden="true" style="font-size: 100px;"></i>
      <i class="fa fa-users" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
    </div>
  <div class="ipsBox">
    <form action="" method="POST">
      
      <table id="sarpTable" class='ipsPad'>
  <tr class="header">	
            <th></th>
            <th  data-key="Pracownik">					
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Pracownik</strong></h5>
              </div>
            </th>	 
            <th  data-key="Ranga">					
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Wypłata $/min</strong></h5>
              </div>
            </th>
            <th data-key="Czas duty">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Czas duty</strong></h5>
              </div>
            </th>
            <th data-key="Ostatnia aktywność">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Ostatnia blokada duty</strong></h5>
              </div>
            </th>
            {{if $perm & 1}}
            <th data-key="Usuwanie">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>&nbsp;</strong></h5>
              </div>
            </th>
            {{endif}}
          </tr>
        {{foreach $groupWorkers as $row}}
 <tr class="ipsClearfix" data-keynavblock="">	
            <td></td>
            <td data-title="Pracownik">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <a href="http://sa-rp.pl/index.php?/profile/{$row['gid']}-redirect/" data-ipshover="" data-ipshover-target="http://sa-rp.pl/index.php?/profile/{$row['gid']}-redirect/&do=hovercard" class="ipsUserPhoto ipsUserPhoto_tiny">
                  <img src="{$row['photo']}">
                </a>
                <h5 class="ipsDataItem_title">{$row['group_player_name']}</h5>
              </div>
            </td>   
           <td data-title="Ranga">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><span style="color:green;">$</span>{$row['group_payday']}/min</h5>
              </div>
            </td>   
            <td data-title="Czas duty">
              {{if $row['group_time'] >= 1}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">
                  <div class="ipsDataItem_title ipsType_positive"><i data-ipstooltip="" _title="Kwalifikuje się do wypłaty" class="fa fa-check-circle"></i>
                    {$row['group_time']} min</div>
                </h5></div>
              {{else}}
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">
                  <div class="ipsDataItem_title ipsType_negative"><i data-ipstooltip="" _title="Nie kwalifikuje się do wypłaty" class="fa fa-times-circle"></i>
                    {$row['group_time']} min</div>
                </h5></div>
              {{endelse}} {{endif}}
            </td>
            <td data-title="Ostatnia aktywność">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{{if $row['czy_online'] == 1}} <span class="ipsType_success">Aktualnie w grze</span> {{else}}{{if $row['group_block_duty'] != 0}}  {datetime="$row['group_block_duty']"} {{else}} <div class="ipsDataItem_title ipsType_negative"><i data-ipstooltip="" _title="Ten gracz nigdy nie wbił pełnego duty i ani raz nie miał blokady duty na 12 godzin w tej grupie." class="fa fa-times-circle"></i> Nie wbił nigdy pełnego duty</div>{{endif}}{{endelse}} {{endif}}</h5></div>
            </td>
            {{if $perm & 447}}
            {{if $row['player_uid'] != \IPS\Request::i()->char_id}}
            <td data-title="Usuwanie">
              <div class="ipsType_sectionTitle ipsType_reset ipsType_center cForumTitle">
                <a href='index.php?app=game&module=group&tab=employees&char_id={expression="\IPS\Request::i()->char_id"}&group_id={expression="\IPS\Request::i()->group_id"}&delete={$row["char_uid"]}' class="ipsType_normal  ipsFaded_withHover" data-ipstooltip="" _title="Usuń postać z tej grupy" style=""><i class="fa fa-times fa-lg"></i></a>
              </div>
            </td>{{endif}}
            {{endif}}
          </tr>
        {{endforeach}}
</table>
       {{if $perm & 64646}}
          <div class="ipsType_center ipsPad ipsAreaBackground_light">
              <input t class='ipsButton ipsButton_primary ipsButton_small' type="submit" value="Zapisz pracowników">
          </div>
        {{endif}}
    </form>
  </div>
  {{endelse}}
  </div>
  {{endif}}
  <br />
  {{if $perm & 146464}}
  <div class="ipsColumns">
    <div class="ipsColumn_fluid">
      <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
        <h4 class="ipsDataItem_title"><strong>Dodawanie nowego pracownika</strong></h4><br>
      </div>
      <ul class="ipsDataList ipsBox ipsPad">
        <div class="ipsColumn ipsColumn_wide ipsType_center">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h5 class="ipsDataItem_title">
              <strong>
                <form action="" method="POST">
                  <label for="new_name">Nick: 
                  </label>
                  <input class="ipsField_short" name="new_name" type="text" placeholder="Imie_Nazwisko">
                  <label for="new_rank" style="margin-left: 10px;">Ranga:</label>
                  <select name="new_rank">
                    {{foreach $groupRanks as $rank}}
                    <option value="{$rank['uid']}">{$rank['name']}</option>
                    {{endforeach}}
                  </select>
                  <input class='ipsButton ipsButton_primary ipsButton_verySmall' type="submit" value="Dodaj pracownika" style="margin-left: 10px; margin-top: 10px">
                </form>
              </strong>
            </h5>
          </div>
        </div>
      </ul>
    </div>
    <div>         
    </div>
    <div style="clear: both"></div>
  </div>
  {{endif}}
</div>