<ips:template parameters="$groups, $perm" />
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i;
  input = document.getElementById("sarpInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("sarpTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[1];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}
</script>   
<div class='ipsPad'>
  
  <div class='ipsType_center'>
	  <input type="text" id="sarpInput" onkeyup="myFunction()" placeholder="Szukaj grupe po nazwie">
  </div>

 <table id="sarpTable" class='ipsPad'>
  <tr class="header">
    <th>ID</th>
    <th>Nazwa</th>
    <th>Dotacja</th>
    <th>Typ grupy</th>
    <th>Zarządzaj</th>
  </tr>
  {{foreach $groups as $row}}
    	<tr>
          <td>
            {$row['id']}
          </td>
          <td>
            {$row['desc']}
          </td>
          <td>
            ${$row['dotacja']}
          </td>
          <td>
            {$row['kind']}
          </td>
          <td>
             <a class="ipsButton ipsButton_verySmall ipsButton_veryLight" data-ipsdialog data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Panel burmistrza &rsaquo;&rsaquo; Zarządzanie grupą"
               href="index.php?app=game&module=group&tab=government&char_id={expression="\IPS\Request::i()->char_id"}&group_id={expression="\IPS\Request::i()->group_id"}&editGroup={$row['id']}">
                <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  <h5 class="ipsDataItem_title">Zarządzaj</h5></div>
              </a>
          </td>
      </tr>
  {{endforeach}}
</table>

</div>