<ips:template parameters="$groupRanks, $perm" />
<div style="background-color: #e6e8eb">
  Nadawanie uprawnień pozostaje póki co w grze. - w trakcie prac.
</div>
 <!-- {{if !$groupRanks}}
   <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <div class="ipsPad">
    <div class='ipsMessage ipsMessage_warning'>
      Grupa nie posiada żadnych stworzonych rang.
    </div>
  </div>
  {{else}}
  <div style="background-color: #e6e8eb; margin-top: -15px;">
    <div style="text-align: center; margin-bottom: 15px;">
      <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
      <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px;"></i>
      <i class="fa fa-list-ol" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
    </div>
  <section id="elProfileTabContent" class="ipsBox">
    <form action="" method="POST">
      
       <table id="sarpTable" class='ipsPad'>
   <tr class="header">	
            <th>
            </th>
            <th  data-key="Nazwa">					
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Nazwa</strong></h5>
              </div>
            </th>					
            <th  data-key="Przejazd">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Ubranie</strong></h5>
              </div>
            </th> 
            <th data-key="Wypłata">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title"><strong>Wypłata</strong></h5>
              </div>
            </th> 
            <th data-ipstooltip="" _title="Dostęp do pojazdów" data-key="Pojazdy">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle ipsType_center">
                <h5 class="ipsDataItem_title"><strong><span class='ipsBadge ipsBadge_primary ipsBadge_large' style="background: #4D5056">V</span></strong></h5>
              </div>
            </th>           
            <th data-ipstooltip="" _title="Zarządzanie drzwiami" data-key="Zarządzanie drzwiami">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle ipsType_center">
                <h5 class="ipsDataItem_title"><strong><span class='ipsBadge ipsBadge_primary ipsBadge_large' style="background: #4D5056">D</span></strong></h5>
              </div>
            </th>           
            <th data-ipstooltip="" _title="Lider" data-key="Lider">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle ipsType_center">
                <h5 class="ipsDataItem_title"><strong><span class='ipsBadge ipsBadge_primary ipsBadge_large' style="background: #4D5056">L</span></strong></h5>
              </div>
            </th>           
            <th data-ipstooltip="" _title="Usuwanie z grupy" data-key="Usuwanie z grupy">	
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle ipsType_center">
                <h5 class="ipsDataItem_title"><strong><span class='ipsBadge ipsBadge_negative ipsBadge_large'>USUŃ</span></strong></h5>
              </div>
            </th>
          </tr>
      {{foreach $groupRanks as $row}}
          <tr class="ipsClearfix" data-keynavblock="">	
            <td></td>
            <td data-title="Nazwa">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['group_player_name']}</h5></div> 
            </td> 			
            <td data-title="Ubrania">
              <a class="ipsButton ipsButton_verySmall ipsButton_veryLight" {{if $perm & 1}}href="#skin" data-ipsDialog data-ipsDialog-title="Ubranie dla rangi: {$row['group_player_name']}(UID:{$row['group_uid']})" data-ipsDialog-content="#skin_{$row['group_uid']}"{{endif}}>  
                <div style="padding: 2px; border-radius: 2px; margin: 2px;">
                   {{if $row['group_skin'] > 300 || $row['group_skin'] == 1}}<img src="images/skins/unknow.png" width="60" height="120" title="Skin ID: {$row['group_skin']}">   <br/>{{else}} <img src="images/skins/{$row['group_skin']}.png" width="60" height="120" title="Skin ID: {$row['group_skin']}">   <br/>{{endif}}
                </div>
              </a>
            </td>
            {{if $perm & 447}}
            <div id="skin_{$row['uid']}" class='ipsHide'>
              <div class="ipsPad ipsBox">
                <ol class=" ipsGrid ipsGrid_collapsePhone" data-ipsgrid="" data-ipsgrid-equalheights="row" style="">    
                  <div class='ipsMessage ipsMessage_info'>
                     Potrzebujesz więcej skinów? <a href="http://sa-rp.pl/index.php?/character/&tab=tickets"><span class="ipsBadge ipsBadge_new ipsBadge_medium">Wyślij zgłoszenie</span></a>
    			  </div>
		
                    <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsType_center ipsGrid_span2" style='margin-left: 20px'>	    
                      <div>
                         {{if $row['group_skin'] > 300 || $row['group_skin'] == 1}}<img src="https://h-rp.eu/images/skins/unknow.png">   <br/>{{else}} <img src="https://h-rp.eu/images/skins/{$row['group_skin']}.png">   <br/>{{endif}}
                      </div>       
                      <div class="ipsStreamItem_container">
                        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half" >
                          <h1 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
                            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                              <h1 class="ipsDataItem_title">Ubranie: <b>id - {$row['group_skin']}</b></h1>
                              {{if $row['skin'] == $row['group_skin']}}
                              	<span class="ipsNotificationCount">Ustawione</span>
                              {{else}}
                              	 <a href='index.php?app=game&module=group&tab=ranks&char_id={expression="\IPS\Request::i()->char_id"}&group_id={expression="\IPS\Request::i()->group_id"}&updateSkin={$s}&rank={$row['uid']}'>
                                  <span class="ipsNotificationCount" style="background-color: green">Wybierz</span></a>
                              {{endif}}
                              <br>
                            </div>				
                          </h1>
                        </div>
                      </div> 
                    </li>
 
                </ol>
              </div>
            </div>
			{{endif}}
            <td data-title="Wypłata">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                {{if $perm & 447}}
                $ {$row['group_payment']}
                {{else}}
                ${$row['group_payment']}
                {{endif}}
              </div>
            </td>
            <td data-title="Dostęp do pojazdów">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_modCheck">
                <input type="checkbox" name="rankFlag[{$row['uid']}][16]" value="1" id="" data-toggle-id="" {{if !$perm & 4427}}disabled{{endif}} {{if $row['group_perm'] & 16}}checked{{endif}} aria-checked="true" data-ipstoggle="" style="display: none;">
                </h5></div>
            </td>
            <td data-title="Zarządzanie drzwiami">
              <div class="ipsDataItem_modCheck">
                <input type="checkbox" name="rankFlag[{$row['uid']}][8]" value="1" id="" data-toggle-id="" {{if !$perm & 4427}}disabled{{endif}} {{if $row['group_perm'] & 8}}checked{{endif}} aria-checked="true" data-ipstoggle="" style="display: none;">
              </div>
            </td>
            <td data-title="Zarządzanie pracownikami (lider)">
              <div class="ipsDataItem_modCheck">
                <input type="checkbox" name="rankFlag[{$row['uid']}][447]" value="1" id="" data-toggle-id="" {{if !$perm & 4247}}disabled{{endif}} {{if $row['group_perm'] & 447}}checked{{endif}} aria-checked="true" data-ipstoggle="" style="display: none;">
              </div>
            </td>
           
          </tr>
        {{endforeach}}
</table>
       {{if $perm & 447}}
          <div class="ipsType_center ipsPad ipsAreaBackground_light">
              <input t class='ipsButton ipsButton_primary ipsButton_small' type="submit" value="Zapisz rangi">
          </div>  
      {{endif}}
    </form>
  </section>
  </div>
  {{endelse}}
  {{endif}}
  {{if $perm & 447}}
  <br />
  <br />
  <div class="ipsColumns">
    <div class="ipsColumn_fluid">
      <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
        <h4 class="ipsDataItem_title"><strong>Tworzenie nowej rangi</strong></h4><br>
      </div>
      <ul class="ipsDataList ipsBox ipsPad">
        <div class="ipsColumn ipsColumn_wide ipsType_center">
          <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
            <h5 class="ipsDataItem_title">
              <strong>
          <form action="" method="POST">
            <label for="new_rankName">Nazwa rangi:</label>
            <input class="ipsField_short" name="new_rankName" type="text" placeholder="">
            <input class='ipsButton ipsButton_primary ipsButton_verySmall' type="submit" value="Stwórz range" style="margin-left: 10px; margin-top: 10px;">
          </form>
              </strong>
            </h5>
          </div>
        </div>
      </ul>
    </div>
    <div>         
    </div>
    <div style="clear: both"></div>
  </div>
  {{endif}}
</div>-->