<ips:template parameters="$tab, $output, $char_id, $group_id, $group_uid" />
<div class=" ipsType_minorHeading ipsType_reset cForumTitle ipsType_right ipsType_huge">
  <h1 class="ipsDataItem_title ipsType_veryLarge"><strong><font color="#828E99">{$group_uid['group_name']}</font> <span style="opacity: 0.5">&#x25C2;</span> <span style="opacity: 0.2">ID: {$group_uid['group_uid']}</span></strong></h1>
  </div>
<div class="ipsBox ipsBox_transparent ipsAreaBackground" data-ipsTabBar data-ipsTabBar-contentArea='#GroupsContent' data-ipsTabBar-itemSelector='.ipsSideMenu_item' data-ipsTabBar-activeClass='ipsSideMenu_itemActive'>
  <div class="ipsColumns ipsColumns_collapsePhone ipsColumns_bothSpacing">
    <div class="ipsColumn ipsColumn_wide saSideMenu">
      <div class="ipsSideMenu">
        <ul class="ipsSideMenu_list">
          <li>
            <a href="index.php?app=game&module=group&tab=dashboard&char_id={$char_id}&group_id={$group_id}" class="href_tab_1 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'dashboard'}}ipsSideMenu_itemActive{{endif}}" title="Podsumowanie">
              <i class="fa fa-dashboard fa-lg"></i>&nbsp; Dashboard
            </a>
          </li>
          <li>
            <a href="?app=game&module=group&tab=employees&char_id={$char_id}&group_id={$group_id}" class="href_tab_2 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'employees'}}ipsSideMenu_itemActive{{endif}}" title="Grupy">
              <i class="fa fa-users fa-lg"></i>&nbsp; Pracownicy
            </a>
          </li>    
          <li>
            <a href="?app=game&module=group&tab=ranks&char_id={$char_id}&group_id={$group_id}" class="href_tab_6 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'ranks'}}ipsSideMenu_itemActive{{endif}}" title="Rangi">
              <i class="fa fa-list-ol fa-lg"></i>&nbsp; Rangi
            </a>
          </li>
          <li>
          <li>
            <a href="?app=game&module=group&tab=vehicles&char_id={$char_id}&group_id={$group_id}" class="href_tab_3 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'vehicles'}}ipsSideMenu_itemActive{{endif}}" title="Pojazdy">
              <i class="fa fa-truck fa-lg"></i>&nbsp; Pojazdy
            </a>
          </li>
          <li>
            <a href="?app=game&module=group&tab=magazine&char_id={$char_id}&group_id={$group_id}" class="href_tab_4 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'magazine'}}ipsSideMenu_itemActive{{endif}}" title="Pojazdy">
              <i class="fa fa-cubes fa-lg"></i>&nbsp; Magazyn
            </a>
          </li>
          <li>
            <a href="?app=game&module=group&tab=doors&char_id={$char_id}&group_id={$group_id}" class="href_tab_5 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'doors'}}ipsSideMenu_itemActive{{endif}}" title="Posiadłości">
              <i class="fa fa-building fa-lg"></i>&nbsp; Nieruchomości
            </a>
          </li>
          <!--<li>
            <a href="?app=game&module=group&tab=transactions&char_id={$char_id}&group_id={$group_id}" class="href_tab_6 saGroupHref ipsType_normal ipsSideMenu_item {{if $tab === 'transactions'}}ipsSideMenu_itemActive{{endif}}" title="Transakcje">
              <i class="fa fa-line-chart fa-lg"></i>&nbsp; Transakcje
            </a>
          </li>
          {{if $groupData['flags'] & 16384}}
          <li style='margin-top: 15px'>
            <a href="?app=game&module=group&tab=government&char_id={$char_id}&group_id={$group_id}" class="href_tab_7 saGroupHref ipsSideMenu_item {{if $tab === 'government'}}ipsSideMenu_itemActive{{endif}}" title="Panel burmistrza">
              <i class="fa fa-bank fa-lg"></i>&nbsp; <span class="ipsType_warning">Panel burmistrza</span>
            </a>
          </li>
          {{endif}}
          <li style='margin-top: 15px' class='ipsAreaBackground_light ipsPad'>
            <a href="index.php?app=game&module=character&controller=character&tab=groups" class="ipsSideMenu_title ipsType_small" title="Powrót">
              <i class="fa fa-undo fa-lg"></i>&nbsp; Powrót do grup
            </a>
          </li>-->
        </ul>
      </div>
    </div>
    <div class="saGroupTab ipsColumn_fluid tab_1" style="display: block; top: -20px">     
      <section id="GroupsContent">
        <div id="ipsTabs_elSettingsTabs_tab_{$tab}_panel" aria-labelledby="tab_{$tab}" aria-hidden="false">
        <div class="ipsAreaBackground ipsPad">
      <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
    <h4 class="ipsDataItem_title"><strong>Statystyki grupy</strong></h4>
  </div>
  <ol class=" ipsGrid ipsGrid_collapsePhone"  data-ipsgrid="" data-ipsgrid-equalheights="row" style="margin-top: -30px; margin-bottom: -40px;">    

          
          
          <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsPad ipsType_center ipsGrid_span4">	    
      <i class="fa fa-dollar fa-3x ipsType_positive"></i>   
      <div class="ipsStreamItem_container">
        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half">
          <h2 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
            <span class="ipsType_break">${$group_uid['group_cash']}</span>				
          </h2>
          <p class="ipsType_reset ipsType_medium">Gotówka grupy</p>
        </div>
      </div> 
    </li>
          	 <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsPad ipsType_center ipsGrid_span4">	    
      <i class="fa fa-dollar fa-3x ipsType_positive" style="color:#889900;"></i>   
      <div class="ipsStreamItem_container">
        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half">
          <h2 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
            <span class="ipsType_break">${$group_uid['group_capital']}</span>				
          </h2>
          <p class="ipsType_reset ipsType_medium">Kapitał grupy</p>
        </div>
      </div> 
    </li>
     <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsPad ipsType_center ipsGrid_span2">	    
      <i class="fa fa-cubes fa-3x"></i>     
      <div class="ipsStreamItem_container">
        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half">
          <h2 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
            <span class="ipsType_break">{$group_uid['group_color']}</span>				
          </h2>
          <p class="ipsType_reset ipsType_medium">Kolor Grupy</p>
        </div>   
      </div>
    </li>
      <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsPad ipsType_center ipsGrid_span2">	    
      <i class="fa fa-expand fa-3x"></i>     
      <div class="ipsStreamItem_container">
        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half">
          <h2 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
            <span class="ipsType_break">{$group_uid['group_tag']}</span>				
          </h2>
          <p class="ipsType_reset ipsType_medium">Skrót Grupy</p>
        </div>   
      </div>
    </li>
      <li class="ipsStreamItem ipsStreamItem_contentBlock ipsAreaBackground_reset ipsPad ipsType_center ipsGrid_span2">	    
      <i class="fa fa-info fa-3x"></i>     
      <div class="ipsStreamItem_container">
        <div class="ipsStreamItem_header ipsSpacer_top ipsSpacer_half">
          <h2 class="ipsType_reset ipsStreamItem_title ipsTruncate ipsTruncate_line">
            <span class="ipsType_break">{$group_uid['group_activity']}</span>				
          </h2>
          <p class="ipsType_reset ipsType_medium">Aktywność Grupy</p>
        </div>   
      </div>
    </li>
     </ol>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>