<ips:template parameters="$trans" />
{{if !$trans}}
     <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <div class="ipsPad">
    <div class='ipsMessage ipsMessage_warning'>
      Grupa nie posiada żadnych transakcji.
    </div>
  </div>
  {{else}}
<div style="background-color: #e6e8eb; margin-top: -15px;">
  <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-line-chart" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <section id="elProfileTabContent" class="ipsBox">
    <table id="sarpTable" class="ipsPad">
        <tr class="header">		
          <th></th>
          <th  data-key="UID">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>ID</strong></h5></div>
          </th>	
          <th  data-key="Nazwa">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Pracownik</strong></h5></div>
          </th>					
          <th  data-key="Przejazd">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Typ</strong></h5></div>
          </th> 	
          <th  data-key="Przejazd">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Wartość</strong></h5></div>
          </th> 
          <th data-key="Status">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Data</strong></h5></div>
          </th>
        </tr>
       {{foreach $trans as $row}}
        <tr class="ipsClearfix" data-keynavblock="">	
          <td></td>
          <td data-title="ID">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['id']}</h5></div>
          </td>
          <td data-title="Pracownik">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['imie_nazwisko']}</h5></div>
          </td> 			
          <td data-title="Typ">
            <div class="ipsDataItem_title">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">{$row['typ']}</h5></div>
            </div>
          </td> 
           <td data-title="Wartość">
            <div class="ipsDataItem_title">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                  {{if $row['log_type'] == 3}}
                   <h5 class="ipsDataItem_title ipsType_negative">
                 	 <i class="fa fa-arrow-circle-down"></i> ${$row['log_value']} </h5>
                	 {{else}}
                 	  <h5 class="ipsDataItem_title ipsType_positive">
                	  <i class="fa fa-arrow-circle-up"></i> ${$row['log_value']} </h5>
                  	{{endelse}}
                  {{endif}}
               </div>
            </div>
          </td> 
          <td data-title="Data">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">
                <div class="ipsDataItem_title">	{datetime="$row['log_date']"} </div> 
              </h5></div>  
          </td>
        </tr>
      {{endforeach}}
    </table>
  </section>
  </div>
{{endelse}}
{{endif}}