<ips:template parameters="$groupCars" />
<div>
  {{if !$groupCars}}
  <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <div class="ipsPad">
    <div class='ipsMessage ipsMessage_warning'>
      Grupa nie posiada żadnych pojazdów.
    </div>
  </div>
  {{else}}
 <div style="background-color: #e6e8eb; margin-top: -15px;">
  <div style="text-align: center; margin-bottom: 15px;">
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-right: 5px; margin-top: 15px"></i>
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px;"></i>
    <i class="fa fa-truck" aria-hidden="true" style="font-size: 100px; opacity: 0.2; margin-left: 5px"></i>
  </div>
  <section id="elProfileTabContent" class="ipsBox">
    <table id='sarpTable' data-role="table">
      <thead>
        <tr class="header">											
          <th  data-key="UID">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>UID</strong></h5></div>
          </th>					
          <th  data-key="Model">					
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Model</strong></h5></div>
          </th>					
          <th  data-key="HP">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>HP</strong></h5></div>
          </th>
          <th data-key="Przebieg">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Przebieg</strong></h5></div>
          </th>
          <th data-key="Paliwo">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Paliwo</strong></h5></div>
          </th>
          <th data-key="Szczegóły">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Szczegóły</strong></h5></div>
          </th>
          <th data-key="Szczegóły">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title"><strong>Logi</strong></h5></div>
          </th>
        </tr>
      </thead>
      {{foreach $groupCars as $row}}
        <tr class="ipsClearfix" data-keynavblock="">	
          <td class="ipsTable_primary ipsType_light">	
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['uid']}</h5></div>
          </td>
          <td data-title="Model">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['name']}</h5></div>	
          </td>			
          <td class=" ipsTable_primary" data-title="HP">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['f-hp']}</h5></div>
          </td>
          <td data-title="Przebieg">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['f-distance']}km</h5></div>
          </td>
          <td data-title="Paliwo">
            <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
              <h5 class="ipsDataItem_title">{$row['f-fuel']} L</h5></div>
          </td>
          <td data-title="Szczegóły">
              <li id="sarpCarsMore" class="ipsCursor_pointer ipsResponsive_showDesktop ipsResponsive_block" data-ipsmenu="" style="">
                <a href='#' class='ipsButton ipsButton_verySmall ipsButton_link'>Zobacz więcej</a>
              </li>
              <ul id="sarpCarsMore_menu" class="ipsMenu ipsMenu_narrow ipsHide ipsMenu_bottomCenter" animating="false">
                <li class="ipsMenu_item"><span><i class="fa" style="min-width: 30px; top: 15px;">
                  <div  data-ipstooltip="" _title="{$row['color1']}" style="border: 1px #ddd solid; border-radius: 2px; width: 20px; height: 20px; background-color: rgb({$row['c1']})">                 
                  </div></i>
             			 <h5 class="ipsDataItem_title ipsType_sectionTitle ipsType_reset cForumTitle"><b>Kolor pierwszy</b></h5>
                  </span></li>
                <li class="ipsMenu_sep"><hr></li>
                <li class="ipsMenu_item"><span><i class="fa" style="min-width: 30px; top: 15px;">
                  <div  data-ipstooltip="" _title="{$row['color2']}" style="border: 1px #ddd solid; border-radius: 2px; width: 20px; height: 20px; background-color: rgb({$row['c2']})">                 
                  </div></i>
                  	<h5 class="ipsDataItem_title ipsType_sectionTitle ipsType_reset cForumTitle"><b>Kolor drugi</b></h5>
                  </span></li>
                <!--
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Alarm</span></li>
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Immobiliser</span></li>
<li class="ipsMenu_sep"><hr></li>
<li class="ipsMenu_item"><span><i class="fa fa-times ipsType_negative" style="min-width: 30px;"></i>Audio</span></li> -->
              </ul>

            </td>
          <td data-title="Logi pojazdu">
            <a class="ipsButton ipsButton_verySmall ipsButton_link" href="#logipojazdow" data-ipsDialog data-ipsDialog-title="Logi pojazdu: {$row['name']} (UID:{$row['uid']})" data-ipsDialog-content="#logipojazdow_{$row['uid']}">
              <div class="ipsType_sectionTitle ipsType_reset cForumTitle">
                <h5 class="ipsDataItem_title">Wyświetl logi</h5></div>
            </a>
          </td>
          <div id="logipojazdow_{$row['uid']}" class='ipsHide'>
            <div class="ipsPad ipsBox">
              Tutaj kiedyś będą logi dla pojazdu {$row['name']} o UID: {$row['uid']}
            </div>
          </div>
        </tr>
      {{endforeach}}
    </table>
  </section>
 </div>
  {{endelse}}
  {{endif}}
</div>