<ips:template parameters="$todoDataNEWS, $todoDataCHECK, $todoDataDONE, $todoDataTRASH, $countNews, $countCheck, $countDone, $countTrash, $lastcomment" />
<div class="ipsTabs saTabs ipsClearfix" id="ticketsTabs" data-ipstabbar="" data-ipstabbar-contentarea="#ticketsTabContent"> 
<div class='ipsMessage ipsMessage_warning'>
	1. Zanim dodasz nowe zgłoszenie, upewnij się czy już czasem ktoś inny go nie dodał - nie chcemy niczego dublować!<br />
 	2. Jeden znaleziony bug = jedno zgłoszenie. Nie twórz czegoś takiego jak "baza błędów" - takie wpisy będą od razu kasowane. Wszystko musi być rozpisane w osobnym todo. <br />
</div>
  <ul role="tablist" class="ipsList_reset" style="float: left">	

    <a class="ipsTabs_item saTabs_item ipsTabs_activeItem" id="cat_news" role="tab" aria-selected="true">
      <span class="saTabs_count" data-action="quickToggleCount"><strong> <i class="fa fa-info-circle fa-lg"></i> &nbsp; {$countNews} </strong></span>
      Nowe
    </a>
    <a class="ipsTabs_item saTabs_item" id="cat_check" role="tab">
      <span class="saTabs_count" data-action="quickToggleCount"><strong> <i class="fa fa-question-circle fa-lg"></i> &nbsp; {$countCheck} </strong></span>
      Do przetestowania
    </a>
    <a class="ipsTabs_item saTabs_item" id="cat_done" role="tab">
      <span class="saTabs_count" data-action="quickToggleCount"><strong> <i class="fa fa-check-circle fa-lg"></i> &nbsp; {$countDone} </strong></span>
      Ukończone
    </a>    
    <a class="ipsTabs_item saTabs_item" id="cat_trash" role="tab">
      <span class="saTabs_count" data-action="quickToggleCount"><strong> <i class="fa fa-times-circle fa-lg"></i> &nbsp; {$countTrash} </strong></span>
      Odrzucone
    </a>	
  </ul>
  <a href="index.php?/todo&action=addTodo" data-ipsdialog data-ipsdialog-modal="true" data-ipsdialog-size="medium" data-ipsdialog-title="Tworzenie zgłoszenia" style="float: right; padding-top: 10px; padding-right: 10px;">
    <span class="ipsBadge ipsBadge_large ipsBadge_positive">
      Stwórz nowe zgłoszenie TO-DO
    </span>
  </a>
</div>
<section id="ticketsTabContent">

  <div id="ipsTabs_ticketsTabs_cat_news_panel" class="ipsTabs_panel" aria-labelledby="cat_news" aria-hidden="false" style="display: block;" animating="false">		
    <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">    
      <hr class="ipsHr">
      <div style="padding-left: 25px; padding-right: 25px; padding-bottom: 25px">	
        <ul class="ipsDataList ipsBox">     
          {{foreach $todoDataNEWS as $row}}
          <li class="ipsDataItem ipsDataItem_responsivePhoto">
            <div class="ipsDataItem_stats" style="min-width: 150px; text-align: center;">
              {{if $row['priority'] == 1}}
              <span class="ipsBadge ipsBadge_large ipsBadge_neutral">
                <strong>Niski</strong>
              </span>
              {{elseif $row['priority'] == 2}}
              <span class="ipsBadge ipsBadge_large ipsBadge_new">
                <strong>Średni</strong>
              </span>
              {{elseif $row['priority'] == 3}}
              <span class="ipsBadge ipsBadge_large  ipsBadge_intermediary">
                <strong>Wysoki</strong>
              </span>
              {{else}}
              <span class="ipsBadge ipsBadge_large  ipsBadge_negative">
                <strong>PRIORYTET</strong>
              </span>
              {{endif}}
            </div>
            <div class="ipsDataItem_main">
              <h4 class="ipsDataItem_title ipsContainer_contained">						
                <div class="ipsType_break ipsContained">
                  <a href="http://h-rp.eu/index.php?app=game&module=todo&id={$row['id']}">
                    {$row['title']}
                  </a>
                </div>
              </h4>
              <div class="ipsDataItem_meta ipsType_light ipsType_blendLinks" data-ipstruncate="" data-ipstruncate-size="2 lines" data-ipstruncate-type="remove" style="word-wrap: break-word;">	
                [#{$row['id']}]
                <span style="margin-left: 10px">
                {{if $row['type'] == 1}}
                <i class="fa fa-comments"></i> 
                Forum
                {{elseif $row['type'] == 2}}
                <i class="fa fa-gamepad"></i> 
                Gra
                {{else}}
                Discord
                {{endelse}}
                {{endif}}
                </span>
                   <span style="margin-left: 15px">
                Dodane przez  <strong><a href="http://h-rp.eu/index.php?/profile/{$row['admin_id']}-redirect/">{$row['nick']}</a></strong>, {datetime="$row['date']"}
                </span>
                  </div>
            </div>
            {{if $row['ilosc_k'] == 0}}
              <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li class="ipsType_light">
                	Brak komentarzy
               </li>
            </ul>
             {{else}}
            <ul class="ipsDataItem_stats">
              <li>
                <span class="ipsDataItem_stats_number">{$row['ilosc_k']}</span>
                <span class="ipsDataItem_stats_type">{{if $row['ilosc_k'] == 0 }} komentarzy {{elseif $row['ilosc_k'] == 1 }} komenatarz {{elseif $row['ilosc_k'] == 2 OR $row['ilosc_k'] == 3 OR $row['ilosc_k'] == 4 }} komentarze {{elseif $row['ilosc_k'] > 4 }} komentarzy {{endelse}} {{endif}}</span>
              </li>
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">
                  <img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$row['avatarAuthor']}">
                </a>		
              </li>
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">{$row['author2']}</a>
              </li>
              <li class="ipsType_light">
                {datetime="$row['time']"}
              </li>
            </ul>  
                          {{endelse}}
                {{endif}}
            {{endforeach}}
          </div>     
        </ol>
      </div>
    <div id="ipsTabs_ticketsTabs_cat_check_panel" class="ipsTabs_panel" aria-labelledby="cat_check" aria-hidden="false" style="display: block;" animating="false">		
      <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">    
        <div style="padding: 25px;">	
          <ul class="ipsDataList ipsBox">
            {{foreach $todoDataCHECK as $row}}
            <li class="ipsDataItem ipsDataItem_responsivePhoto">
              <div class="ipsDataItem_stats" style="min-width: 150px; text-align: center;">
                {{if $row['priority'] == 1}}
                <span class="ipsBadge ipsBadge_large ipsBadge_neutral">
                  <strong>Niski</strong>
                </span>
                {{elseif $row['priority'] == 2}}
                <span class="ipsBadge ipsBadge_large ipsBadge_new">
                  <strong>Średni</strong>
                </span>
                {{elseif $row['priority'] == 3}}
                <span class="ipsBadge ipsBadge_large  ipsBadge_intermediary">
                  <strong>Wysoki</strong>
                </span>
                {{else}}
                <span class="ipsBadge ipsBadge_large  ipsBadge_negative">
                  <strong>PRIORYTET</strong>
                </span>
                {{endif}}
              </div>
              <div class="ipsDataItem_main">
                <h4 class="ipsDataItem_title ipsContainer_contained">						
                  <div class="ipsType_break ipsContained">
                    <a href="http://h-rp.eu/index.php?app=game&module=todo&id={$row['id']}">
                      {$row['title']}
                    </a>
                  </div>
                </h4>
                <div class="ipsDataItem_meta ipsType_light ipsType_blendLinks" data-ipstruncate="" data-ipstruncate-size="2 lines" data-ipstruncate-type="remove" style="word-wrap: break-word;">	
                [#{$row['id']}]
                <span style="margin-left: 10px">
                {{if $row['type'] == 1}}
                <i class="fa fa-comments"></i> 
                Forum
                {{elseif $row['type'] == 2}}
                <i class="fa fa-gamepad"></i> 
                Gra
                {{else}}
                Discord
                {{endelse}}
                {{endif}}
                </span>
                   <span style="margin-left: 15px">
                Dodane przez  <strong><a href="http://h-rp.eu/index.php?/profile/{$row['admin_id']}-redirect/">{$row['nick']}</a></strong>, {datetime="$row['date']"}
                </span>
                  </div>
            </div>
            {{if $row['ilosc_k'] == 0}}
              <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li class="ipsType_light">
                	Brak komentarzy
               </li>
            </ul>
             {{else}}
            <ul class="ipsDataItem_stats">
              <li>
                <span class="ipsDataItem_stats_number">{$row['ilosc_k']}</span>
                <span class="ipsDataItem_stats_type">{{if $row['ilosc_k'] == 0 }} komentarzy {{elseif $row['ilosc_k'] == 1 }} komenatarz {{elseif $row['ilosc_k'] == 2 OR $row['ilosc_k'] == 3 OR $row['ilosc_k'] == 4 }} komentarze {{elseif $row['ilosc_k'] > 4 }} komentarzy {{endelse}} {{endif}}</span>
              </li>
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">
                  <img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$row['avatarAuthor']}">
                </a>		
              </li>
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">{$row['author2']}</a>
              </li>
              <li class="ipsType_light">
                {datetime="$row['time']"}
              </li>
            </ul>  
                          {{endelse}}
                {{endif}}
            {{endforeach}}
          </div>     
        </ol>
      </div>
      <div id="ipsTabs_ticketsTabs_cat_done_panel" class="ipsTabs_panel" aria-labelledby="cat_done" aria-hidden="false" style="display: block;" animating="false">		
        <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">    
          <div style="padding: 25px;">
            <ul class="ipsDataList ipsBox">
              {{foreach $todoDataDONE as $row}}
              <li class="ipsDataItem ipsDataItem_responsivePhoto">
                <div class="ipsDataItem_stats" style="min-width: 150px; text-align: center;">
                  {{if $row['priority'] == 1}}
                  <span class="ipsBadge ipsBadge_large ipsBadge_neutral">
                    <strong>Niski</strong>
                  </span>
                  {{elseif $row['priority'] == 2}}
                  <span class="ipsBadge ipsBadge_large ipsBadge_new">
                    <strong>Średni</strong>
                  </span>
                  {{elseif $row['priority'] == 3}}
                  <span class="ipsBadge ipsBadge_large  ipsBadge_intermediary">
                    <strong>Wysoki</strong>
                  </span>
                  {{else}}
                  <span class="ipsBadge ipsBadge_large  ipsBadge_negative">
                    <strong>PRIORYTET</strong>
                  </span>
                  {{endif}}
                </div>
                <div class="ipsDataItem_main">
                  <h4 class="ipsDataItem_title ipsContainer_contained">						
                    <div class="ipsType_break ipsContained">
                      <a href="http://h-rp.eu/index.php?app=game&module=todo&id={$row['id']}">
                        {$row['title']}
                      </a>
                    </div>
                  </h4>
                  <div class="ipsDataItem_meta ipsType_light ipsType_blendLinks" data-ipstruncate="" data-ipstruncate-size="2 lines" data-ipstruncate-type="remove" style="word-wrap: break-word;">	
                [#{$row['id']}]
                <span style="margin-left: 10px">
                {{if $row['type'] == 1}}
                <i class="fa fa-comments"></i> 
                Forum
                {{elseif $row['type'] == 2}}
                <i class="fa fa-gamepad"></i> 
                Gra
                {{else}}
                Discord
                {{endelse}}
                {{endif}}
                </span>
                   <span style="margin-left: 15px">
                Dodane przez  <strong><a href="http://h-rp.eu/index.php?/profile/{$row['admin_id']}-redirect/">{$row['nick']}</a></strong>, {datetime="$row['date']"}
                </span>
                  </div>
            </div>
            {{if $row['ilosc_k'] == 0}}
              <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li class="ipsType_light">
                	Brak komentarzy
               </li>
            </ul>
             {{else}}
            <ul class="ipsDataItem_stats">
              <li>
                <span class="ipsDataItem_stats_number">{$row['ilosc_k']}</span>
                <span class="ipsDataItem_stats_type">{{if $row['ilosc_k'] == 0 }} komentarzy {{elseif $row['ilosc_k'] == 1 }} komenatarz {{elseif $row['ilosc_k'] == 2 OR $row['ilosc_k'] == 3 OR $row['ilosc_k'] == 4 }} komentarze {{elseif $row['ilosc_k'] > 4 }} komentarzy {{endelse}} {{endif}}</span>
              </li>
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">
                  <img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$row['avatarAuthor']}">
                </a>		
              </li>
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">{$row['author2']}</a>
              </li>
              <li class="ipsType_light">
                {datetime="$row['time']"}
              </li>
            </ul>  
                          {{endelse}}
                {{endif}}
            {{endforeach}}
          </div>     
        </ol>
      </div>
        <div id="ipsTabs_ticketsTabs_cat_trash_panel" class="ipsTabs_panel" aria-labelledby="cat_trash" aria-hidden="false" style="display: block;" animating="false">		
          <ol class="ipsBox ipsDataList ipsDataList_large ipsDataList_zebra ipsAreaBackground_reset cForumList" data-role="market" style="border-top: 0;">    
            <div style="padding: 25px;">	
              <ul class="ipsDataList ipsBox">
                {{foreach $todoDataTRASH as $row}}
                <li class="ipsDataItem ipsDataItem_responsivePhoto">
                  <div class="ipsDataItem_stats" style="min-width: 150px; text-align: center;">
                    {{if $row['priority'] == 1}}
                    <span class="ipsBadge ipsBadge_large ipsBadge_neutral">
                      <strong>Niski</strong>
                    </span>
                    {{elseif $row['priority'] == 2}}
                    <span class="ipsBadge ipsBadge_large ipsBadge_new">
                      <strong>Średni</strong>
                    </span>
                    {{elseif $row['priority'] == 3}}
                    <span class="ipsBadge ipsBadge_large  ipsBadge_intermediary">
                      <strong>Wysoki</strong>
                    </span>
                    {{else}}
                    <span class="ipsBadge ipsBadge_large  ipsBadge_negative">
                      <strong>PRIORYTET</strong>
                    </span>
                    {{endif}}
                  </div>
                  <div class="ipsDataItem_main">
                    <h4 class="ipsDataItem_title ipsContainer_contained">						
                      <div class="ipsType_break ipsContained">
                        <a href="http://h-rp.eu/index.php?app=game&module=todo&id={$row['id']}">
                          {$row['title']}
                        </a>
                      </div>
                    </h4>
                   <div class="ipsDataItem_meta ipsType_light ipsType_blendLinks" data-ipstruncate="" data-ipstruncate-size="2 lines" data-ipstruncate-type="remove" style="word-wrap: break-word;">	
                [#{$row['id']}]
                <span style="margin-left: 10px">
                {{if $row['type'] == 1}}
                <i class="fa fa-comments"></i> 
                Forum
                {{elseif $row['type'] == 2}}
                <i class="fa fa-gamepad"></i> 
                Gra
                {{else}}
                Discord
                {{endelse}}
                {{endif}}
                </span>
                   <span style="margin-left: 15px">
                Dodane przez  <strong><a href="http://h-rp.eu/index.php?/profile/{$row['admin_id']}-redirect/">{$row['nick']}</a></strong>, {datetime="$row['date']"}
                </span>
                  </div>
            </div>
            {{if $row['ilosc_k'] == 0}}
              <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li class="ipsType_light">
                	Brak komentarzy
               </li>
            </ul>
             {{else}}
            <ul class="ipsDataItem_stats">
              <li>
                <span class="ipsDataItem_stats_number">{$row['ilosc_k']}</span>
                <span class="ipsDataItem_stats_type">{{if $row['ilosc_k'] == 0 }} komentarzy {{elseif $row['ilosc_k'] == 1 }} komenatarz {{elseif $row['ilosc_k'] == 2 OR $row['ilosc_k'] == 3 OR $row['ilosc_k'] == 4 }} komentarze {{elseif $row['ilosc_k'] > 4 }} komentarzy {{endelse}} {{endif}}</span>
              </li>
            </ul>
            <ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto ipsType_blendLinks">
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">
                  <img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$row['avatarAuthor']}">
                </a>		
              </li>
              <li>
                <a href="http://h-rp.eu/index.php?/profile/{$row['author']}-redirect/">{$row['author2']}</a>
              </li>
              <li class="ipsType_light">
                {datetime="$row['time']"}
              </li>
            </ul>  
                          {{endelse}}
                {{endif}}
            {{endforeach}}
          </div>     
        </ol>
      </div>
          </section>