<ips:template parameters="$news, $newsCM, $latestchanges, $allchanges" />
<div class='hrpContainer'  style="">
<div class="saHeroArticle">
   
<img src="https://life-of-german.org/image-proxy/?key=34b886a8f9fc35191d409ddc13b0365a6c96fe06a1f5f5ed7f838565a6353155-aHR0cHM6Ly9maWxlcy5saWZlLW9mLWdlcm1hbi5vcmcvY21zL2ltYWdlcy9sb2dvcy9zYW1wLnBuZw%3D%3D">
<h4>San Andreas MultiPlayer</h4>
<p>Rozwijaj Swoje postacie i zarabiaj pieniądze, na setki sposobów.<br>Wiele skomplikowanych systemów stworzonych z myślą o Tobie, nie czekaj - dołącz już teraz. <br><br>Zostań kim zapragniesz, szeryfem, medykiem, gangsterem, przemytnikiem, rolnikiem, to tylko z nieskończonych możliwości na odgrywanie postaci!</p>
  </div>
  <h1>Mamy łącznie <span class="ipsBadge ipsBadge_medium ipsBadge_positive">{expression="\IPS\game\Character::playersOnline()"}</span> graczy online i <span class="ipsBadge ipsBadge_medium ipsBadge_purple">{expression="\IPS\game\Character::CharacterCount()"}</span> postaci.  <a href="https://discord.gg/yYxnDdq"><img width="40px" height="40px" src="https://f0.pngfuel.com/png/408/238/purple-robot-logo-png-clip-art.png"/></a></h1>


  <p>Mamy obecnie <span class="ipsBadge ipsBadge_medium ipsBadge_positive"><span id="discord-counter"></span></span> aktywnych graczy na discordzie.</p>

  <br>
  <a class="btnhrp2" href="https://discord.gg/yYxnDdq"><img width="40px"  height="40px"src="https://img.icons8.com/clouds/2x/discord-logo.png"> Dołącz do discorda</a>
  

  
  <br><br>
  
  
    <script type="text/javascript">
        var request = new XMLHttpRequest();

        request.open('GET', 'https://discordapp.com/api/guilds/664848834194702336/widget.json', true);

        request.onload = function() {
          if (request.status >= 200 && request.status < 400) {
            // Success!
            var data = JSON.parse(request.responseText);
            document.getElementById("discord-counter").innerHTML = data.members.length;

          } else {
            // We reached our target server, but it returned an error

          }
        };

        request.onerror = function() {
          // There was a connection error of some sort
        };

        request.send();
    </script>
 
<script>
  function switchTabs(chosen)
  {
    $(".saCharacterTab").hide();
    $(".tab_"+chosen).show();
    $('.href_tab_'+chosen).addClass('ipsSideMenu_itemActive');
    $('.saCharacterHref').removeClass('ipsSideMenu_itemActive');
    $('.href_tab_'+chosen).addClass('ipsSideMenu_itemActive');
  }
</script>
<style>
  .ipsSideMenu_itemActive{ border-bottom: 3px solid #fac746;}
  </style>
   <h3 class="hrpTitle" style="font-size:26px;">Nowości</h3>
  <div style="max-width:90%; margin:0 auto;">
    
  <div id="box_left"> 
 
      {{if count( $news )}}		
    {{foreach $news as $topic}} 



    <header>
  <div id="hrpNewsHeader">
                <div id="hrpNewsHeaderAvatar">
<img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$topic['photo']}">
                </div>
                <div id="hrpNewsHeaderText">
                                        <a href="/forums/topic/{$topic["topic_id"]}-redirect/"><h2>{$topic['title']}</h2></a>
                    <h3>{datetime="$topic['start_date']"} przez <a></a><a title="" id="anonymous_element_1"><span itemprop="name"><span style="color: #9424b4;">{$topic['author_name']}</span></span></a></h3>
                </div>
                
            </div>

  </header>

<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="40 lines" class='ipsType_richText ipsType_small' data-controller='core.front.core.lightboxedImages'>
            {$topic['post']|raw}
          </div>
  <div class="subinfo clearfix"><div class="right"  style="text-align:right;">
   <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li class="ipsType_light ipsType_small"><i class='fa fa-comments-o fa-lg'></i> &nbsp; {lang="replies_number" pluralize="$topic['posts']"}</li> 
                <li class="ipsType_light ipsType_small"><i class='fa fa-eye fa-lg'></i> &nbsp;{$topic['views']} wyświetleń</li>
                <span class="ipsType_blendLinks ipsType_small ipsPos_right">
              <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li>	
                  {{if $topic['featured']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_intermediary" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star fa-lg'></i></span></span>
                  {{endif}}
                  {{if $topic['pinned']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack fa-lg'></i></span></span>
                  {{endif}}
                </li>
              </ul>
            </span>
              </ul>
    </div></div>

    {{endforeach}}		
    {{endif}}
    
  </div>

 
<div id="box_right"> 
  <div id="hrpSanNewsHeader">
            <h2>Bone Country News</h2>
            <h3>WIADOMOŚCI LIVE</h3><br>
        </div>
   {{if count( $newsCM )}}		
    {{foreach $newsCM as $topic}} 
  <div class="hentry sarpNews sarpNews1 " style="max-width:100%;">

  <div id="hrpNews" class="ipsTruncate">
    <header>
  <div id="hrpNewsHeader">
                <div id="hrpNewsHeaderAvatar">
<img class="ipsUserPhoto ipsUserPhoto_tiny" src="{$topic['photo']}">
                </div>
                <div id="hrpNewsHeaderText">
                                        <a href="/forums/topic/{$topic["topic_id"]}-redirect/"><h2>{$topic['title']}</h2></a>
                    <h3>{datetime="$topic['start_date']"} przez <a></a><a title="" id="anonymous_element_1"><span itemprop="name"><span style="color: #9424b4;">{$topic['author_name']}</span></span></a></h3>
                </div>
                
            </div>

  </header>

<div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="40 lines" class='ipsType_richText ipsType_small' data-controller='core.front.core.lightboxedImages '>
            {$topic['post']|raw}
          </div>
  <div class="subinfo clearfix"><div class="right"  style="text-align:right;">
   <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li class="ipsType_light ipsType_small"><i class='fa fa-comments-o fa-lg'></i> &nbsp; {lang="replies_number" pluralize="$topic['posts']"}</li> 
                <li class="ipsType_light ipsType_small"><i class='fa fa-eye fa-lg'></i> &nbsp;{$topic['views']} wyświetleń</li>
                <span class="ipsType_blendLinks ipsType_small ipsPos_right">
              <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li>	
                  {{if $topic['featured']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_intermediary" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star fa-lg'></i></span></span>
                  {{endif}}
                  {{if $topic['pinned']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack fa-lg'></i></span></span>
                  {{endif}}
                </li>
              </ul>
            </span>
              </ul>
    </div></div>

    {{endforeach}}		
    {{endif}}


    </div>
  </div>
</div>





   
<div class="clear"></div>
  
      <h3 class="hrpTitle" style="font-size:26px;">Ostatnie zmiany</h3>
    <div class="ipsBox" style="padding: 5px;">
      <ul class="ipsDataList" data-role="statusFeed">
		{{if !$latestchanges}}
        <li class="ipsDataItem  ipsPad" data-statusid="2"> Brak wpisów. </li>
        {{else}}
        {{foreach $latestchanges as $row}}
        <li class="ipsDataItem " data-statusid="2">
          <div class="ipsDataItem_icon ipsPos_top" style='min-width: 60px;'>
            <span class='ipsBadge ipsBadge_medium ipsBadge_new'>#{$row['id']}</span>
            {{if $row['isNew']}}
            <span class='ipsBadge ipsBadge_medium ipsBadge_negative sarpPulse'>NOWE</span>
            {{endif}}
          </div>
          <div class="ipsDataItem_main ipsType_medium ipsType_break">
            <div class="ipsType_richText ipsContained" data-ipstruncate="" data-ipstruncate-type="remove" data-ipstruncate-size="25 lines" data-ipstruncate-watch="false" style="overflow-wrap: break-word;">
              {$row['content']|raw}
              {{if \IPS\Member::loggedIn()->member_group_id == 4 }}
              <a href="https://h-rp.pl/index.php?app=game&module=portal&deleteChange={$row['id']}" class="ipsType_light ipsType_normal ipsPos_right ipsFaded ipsFaded_more ipsFaded_withHover" data-ipstooltip="" data-action="disable" _title="Usuń ten wpis" style=""><i class="fa fa-times"></i></a>
              {{endif}}
              <br>  
            </div>
            <span class="ipsType_light ipsType_small ipsType_blendLinks">Przez {$row['nick']} &nbsp;<i class="fa fa-clock-o"></i>&nbsp;{datetime="$row['date']"}</span> 
          </div>
        </li>
        {{endforeach}}
        {{endelse}}
        {{endif}}
      </ul>
      <div class="ipsMenu_footerBar ipsType_center">
        <a href='#allchanges' data-ipsDialog data-ipsDialog-title="Wszystkie zmiany" data-ipsDialog-content="#allchanges" data-ipsdialog-size="narrow"> 
          <i class="fa fa-bars"></i>&nbsp; Wyświetl wszystkie zmiany</a>
        {{if \IPS\Member::loggedIn()->member_group_id == 4 }}
        <div class="ipsType_center">
          <a href="https://h-rp.eu/index.php?app=game&module=ajax&controller=changes"  class="ipsButton ipsButton_overlaid ipsButton_verySmall" data-ipsdialog="" data-ipsdialog-modal="true" data-ipsdialog-size="narrow" data-ipsdialog-title="Dodaj zmiane">
            <i class="fa fa-pencil"></i>&nbsp;<span class="ipsResponsive_hidePhone ipsResponsive_inline">&nbsp;&nbsp;Dodaj zmiane</span>
          </a>	
        </div>
        {{endif}}
      </div>
      <div id='allchanges' class='ipsHide'>
        <div class='ipsFollowerList ipsScrollbar'>
          <ul style="list-style-type: none; padding: 0; margin:  0;">
            {{if !$allchanges}}
            <li class="ipsDataItem" data-statusid="2">
              Brak wpisów.
            </li>
            {{else}}
            {{foreach $allchanges as $row}}
            <li class="ipsDataItem" data-statusid="2">
              <div class="ipsDataItem_icon ipsPos_top" style='min-width: 60px;'>
                <span class='ipsBadge ipsBadge_medium ipsBadge_new'>#{$row['id']}</span>
                {{if $row['isNew']}}
                <span class='ipsBadge ipsBadge_medium ipsBadge_negative'>NOWE</span>
                {{endif}}
              </div>
              <div class="ipsDataItem_main ipsType_medium ipsType_break">
                <div class="ipsType_richText ipsContained" data-ipstruncate="" data-ipstruncate-type="remove" data-ipstruncate-size="25 lines" data-ipstruncate-watch="false" style="overflow-wrap: break-word;">
                  {$row['content']}
                  {{if \IPS\Member::loggedIn()->member_group_id == 4 }}
                  <a href="index.php?app=game&module=portal&deleteChange={$row['id']}" class="ipsType_light ipsType_normal ipsPos_right ipsFaded ipsFaded_more ipsFaded_withHover" data-ipstooltip="" data-action="disable" _title="Usuń ten wpis" style=""><i class="fa fa-times"></i></a>
                  {{endif}}
                  <br>  
                </div>
                <span class="ipsType_light ipsType_small ipsType_blendLinks">Przez {$row['nick']} &nbsp;<i class="fa fa-clock-o"></i>&nbsp;{datetime="$row['date']"}</span> 
              </div>
            </li>
            {{endforeach}}
            {{endelse}}
            {{endif}}
          </ul>
        </div>
      </div>
    </div>
  </div> 



  
  <!--

  
  
<div class='ipsColumns' style="margin-top: -10px width:100%;" >
  <div class='ipsColumn ipsColumn_fluid'>
    <div class="saCharacterTab ipsColumn_fluid tab_1" style="display: block;">
    

      <h1 class="portal_h1">Informacje dla <span style="color:#9a5f03;">społeczności</span></h1>
      
    {{if count( $news )}}		
    {{foreach $news as $topic}} 
       {{if $topic['topic_id'] != 0 }}
    <ol class='ipsBox ipsStreamItem ipsStreamItem_contentBlock ipsStreamItem_expanded ipsAreaBackground_reset ipsPad' data-role="tableRows" style="">
      <div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix ipsType_medium' >
        <img src='{$topic["photo"]}' alt='' class='ipsUserPhoto ipsUserPhoto_mini'>
        <div>
          <h1 class="ipsType_pageTitle">
            <span data-role="streamTitle" class="ipsType_sectionTitle ipsType_reset cForumTitle" style="font-size: 100%">
            	<a href='index.php?/forums/topic/{$topic["topic_id"]}-redirect/' title='' target='_top'>{$topic['title']}</a></span>
            <span class="ipsType_blendLinks ipsType_small ipsPos_right">
              <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li class="ipsType_light ipsType_small"><i class='fa fa-comments-o fa-lg'></i> &nbsp; {lang="replies_number" pluralize="$topic['posts']"}</li> 
                <li class="ipsType_light ipsType_small"><i class='fa fa-eye fa-lg'></i> &nbsp;{$topic['views']} wyświetleń</li>
                <li>	
                  {{if $topic['featured']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_intermediary" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star fa-lg'></i></span></span>
                  {{endif}}
                  {{if $topic['pinned']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack fa-lg'></i></span></span>
                  {{endif}}
                </li>
              </ul>
            </span>
          </h1>
          <span class="ipsType_light ipsType_small">Przez {$topic['author_name']} &nbsp;<i class="fa fa-clock-o"></i>&nbsp;{datetime="$topic['start_date']"}</span>
          <hr class="ipsHr">
          <div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="35 lines" class='ipsType_richText ipsType_small' data-controller='core.front.core.lightboxedImages'>
            {$topic['post']|raw}
          </div>
        </div>
      </div>
    </ol> 
      {{endif}}
    {{endforeach}}		
    {{endif}}
    </div>
     <br />

 <div class="saCharacterTab ipsColumn_fluid tab_2" style="display: none;">
    
    <h1 class="ipsType_sectionTitle ipsType_reset cForumTitle" style="font-size: 180%">
    
      <strong>Ogłoszenia GameMasterów</strong></h1>
    {{if count( $newsCM )}}		
    {{foreach $newsCM as $topic}} 
    <ol class='ipsBox ipsStreamItem ipsStreamItem_contentBlock ipsStreamItem_expanded ipsAreaBackground_reset ipsPad' data-role="tableRows" style="">
      <div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix ipsType_medium' >
        <img src='{$topic["photo"]}' alt='' class='ipsUserPhoto ipsUserPhoto_mini'>
        <div>
          <h1 class="ipsType_pageTitle">
            <span data-role="streamTitle" class="ipsType_sectionTitle ipsType_reset cForumTitle" style="font-size: 100%">
            	<a href='index.php?/forums/topic/{$topic["topic_id"]}-redirect/' title='' target='_top'>{$topic['title']}</a></span>
            <span class="ipsType_blendLinks ipsType_small ipsPos_right">
              <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li class="ipsType_light ipsType_small"><i class='fa fa-comments-o fa-lg'></i> &nbsp; {lang="replies_number" pluralize="$topic['posts']"}</li> 
                <li class="ipsType_light ipsType_small"><i class='fa fa-eye fa-lg'></i> &nbsp;{$topic['views']} wyświetleń</li>
                <li>	
                  {{if $topic['featured']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_intermediary" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star fa-lg'></i></span></span>
                  {{endif}}
                  {{if $topic['pinned']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack fa-lg'></i></span></span>
                  {{endif}}
                </li>
              </ul>
            </span>
          </h1>
          <span class="ipsType_light ipsType_small">Przez {$topic['author_name']} &nbsp;<i class="fa fa-clock-o"></i>&nbsp;{datetime="$topic['start_date']"}</span>
          <hr class="ipsHr">
          <div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="35 lines" class='ipsType_richText ipsType_small' data-controller='core.front.core.lightboxedImages'>
            {$topic['post']|raw}
          </div>
        </div>
      </div>
    </ol> 
    {{endforeach}}		
    {{endif}}
    </div>
     <br />
<div class="saCharacterTab ipsColumn_fluid tab_3" style="display: none;">
    
    <h1 class="ipsType_sectionTitle ipsType_reset cForumTitle" style="font-size: 180%">
    
      <strong>Aktualność z życia LSPD</strong></h1>
    {{if count( $newsLSPD )}}		
    {{foreach $newsLSPD as $topic}} 
    <ol class='ipsBox ipsStreamItem ipsStreamItem_contentBlock ipsStreamItem_expanded ipsAreaBackground_reset ipsPad' data-role="tableRows" style="">
      <div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix ipsType_medium' >
        <img src='{$topic["photo"]}' alt='' class='ipsUserPhoto ipsUserPhoto_mini'>
        <div>
          <h1 class="ipsType_pageTitle">
            <span data-role="streamTitle" class="ipsType_sectionTitle ipsType_reset cForumTitle" style="font-size: 100%">
            	<a href='index.php?/forums/topic/{$topic["topic_id"]}-redirect/' title='' target='_top'>{$topic['title']}</a></span>
            <span class="ipsType_blendLinks ipsType_small ipsPos_right">
              <ul class='ipsList_inline ipsType_small ipsClearfix'>
                <li class="ipsType_light ipsType_small"><i class='fa fa-comments-o fa-lg'></i> &nbsp; {lang="replies_number" pluralize="$topic['posts']"}</li> 
                <li class="ipsType_light ipsType_small"><i class='fa fa-eye fa-lg'></i> &nbsp;{$topic['views']} wyświetleń</li>
                <li>	
                  {{if $topic['featured']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_intermediary" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star fa-lg'></i></span></span>
                  {{endif}}
                  {{if $topic['pinned']}}
                  <span><span class="ipsBadge ipsBadge_icon ipsBadge_big ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack fa-lg'></i></span></span>
                  {{endif}}
                </li>
              </ul>
            </span>
          </h1>
          <span class="ipsType_light ipsType_small">Przez {$topic['author_name']} &nbsp;<i class="fa fa-clock-o"></i>&nbsp;{datetime="$topic['start_date']"}</span>
          <hr class="ipsHr">
          <div data-ipsTruncate data-ipsTruncate-type="hide" data-ipsTruncate-size="35 lines" class='ipsType_richText ipsType_small' data-controller='core.front.core.lightboxedImages'>
            {$topic['post']|raw}
          </div>
        </div>
      </div>
    </ol> 
    {{endforeach}}		
    {{endif}}
    </div>
     <br />
  </div>


     
 
    
     
    
    
   
  </div> 

            
 
   
  </div>
  
-->
  






  
  